### ISSUE TITLE
asyncio.base_futures.InvalidStateError: invalid state

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1874]
## The Issue
Both @jackrobison and I have run into this, but not sure why yet. Victor had put in a fix during earlier testing and it happens much less often.
```

2019-02-07 07:16:36,809 INFO     lbrynet.dht.blob_announcer:45: announced 2 blobs
2019-02-07 07:20:26,954 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=515547, change=1) header blocks, final height 515547
2019-02-07 07:20:31,969 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=515548, change=1) header blocks, final height 515548
2019-02-07 07:20:46,764 INFO     lbrynet.blob_exchange.server:67: sent f71a08fb (2097152 bytes) to 81.39.44.21:59664
2019-02-07 07:20:48,778 INFO     lbrynet.blob_exchange.server:67: sent 6a2ca3a6 (2097152 bytes) to 81.39.44.21:59664
Exception in callback _SelectorSocketTransport._call_connection_lost(ConnectionAbo..., 10053, None))
handle: <Handle _SelectorSocketTransport._call_connection_lost(ConnectionAbo..., 10053, None))>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\selector_events.py", line 927, in _call_connection_lost
asyncio.base_futures.InvalidStateError: invalid state
```

```2019-02-07 04:31:47,490 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=515485, change=1) header blocks, final height 515485
2019-02-07 04:32:07,106 INFO     lbrynet.blob_exchange.server:67: sent 07510635 (2097152 bytes) to 88.186.128.202:57516
Exception in callback _SelectorSocketTransport._call_connection_lost(ConnectionAbo..., 10053, None))
handle: <Handle _SelectorSocketTransport._call_connection_lost(ConnectionAbo..., 10053, None))>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\selector_events.py", line 927, in _call_connection_lost
asyncio.base_futures.InvalidStateError: invalid state
2019-02-07 04:32:57,608 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=515486, change=1) header blocks, final height 515486
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
We believe this happens when you are sending a blob and the client drops the connection.

**Comment by alyssaoc** [comment]
need to add a test for this

**Comment by tzarebczan** [comment]
This is no longer happening, re-open if you run across it.
