### ISSUE TITLE
assertion error when attempting upnp - prevents startup

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1917]
## The Issue
SDK fails to startup with the below errror. UPNP is disabled /unavailable.  Turning off upnp works. Might be related to https://github.com/lbryio/lbry/issues/1886? 
```2019-02-15 08:54:53,538 WARNING  lbrynet.extras.daemon.Components:523: upnp discovery failed: M-SEARCH for 192.168.1.1:1900 timed out
2019-02-15 08:54:53,540 WARNING  lbrynet.extras.daemon.Components:537: unable to get external ip from UPnP, checking lbry.io fallback
2019-02-15 08:54:53,929 ERROR    lbrynet.extras.daemon.Component:61: Error setting up upnp
Traceback (most recent call last):
  File "lbrynet/extras/daemon/Component.py", line 55, in _setup
  File "lbrynet/extras/daemon/Components.py", line 592, in start
  File "lbrynet/extras/daemon/Components.py", line 542, in _maintain_redirects
AssertionError
```

In 0.30.4, they would see
```2019-02-15 08:08:32,521 WARNING  lbrynet.extras.daemon.Components:651: upnp discovery failed: M-SEARCH for 192.168.1.1:1900 timed out
2019-02-15 08:08:32,521 WARNING  lbrynet.extras.daemon.Components:665: unable to get external ip from UPnP, checking lbry.io fallback
2019-02-15 08:08:57,168 ERROR    asyncio:1597: Task exception was never retrieved
future: <Task finished coro=<Gateway._discover_gateway() done, defined at site-packages/aioupnp/gateway.py:157> exception=UPnPError('M-SEARCH for 192.168.1.1:1900 timed out')>
Traceback (most recent call last):
  File "site-packages/aioupnp/gateway.py", line 169, in _discover_gateway
  File "site-packages/aioupnp/protocols/ssdp.py", line 173, in fuzzy_m_search
  File "site-packages/aioupnp/protocols/ssdp.py", line 166, in _fuzzy_m_search
aioupnp.fault.UPnPError: M-SEARCH for 192.168.1.1:1900 timed out
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by hackrush01** [comment]
Does this happen when your port is already mapped?

**Comment by tzarebczan** [comment]
Nope, I think you run into a different warning, but it still starts up. I'll double check.

**Comment by tzarebczan** [comment]
This is still an issue, a user recently ran into: ```2019-08-14 20:11:28,691 INFO     lbry.extras.daemon.Components:482: found upnp gateway: AVM Berlin WANConnectionDevice - FRITZ!Box Fon WLAN 7390
2019-08-14 20:11:28,706 ERROR    lbry.extras.daemon.Component:62: Error setting up upnp
Traceback (most recent call last):
  File "lbry\extras\daemon\Component.py", line 55, in _setup
  File "lbry\extras\daemon\Components.py", line 562, in start
  File "lbry\extras\daemon\Components.py", line 493, in _maintain_redirects
  File "site-packages\aioupnp\upnp.py", line 122, in get_external_ip
  File "site-packages\aioupnp\commands.py", line 231, in GetExternalIPAddress
  File "site-packages\aioupnp\commands.py", line 153, in wrapper
  File "site-packages\aioupnp\commands.py", line 42, in recast_return
KeyError: 'NewExternalIPAddress'```

**Comment by tzarebczan** [comment]
This should no longer happen with latest aioupnp

**Comment by VivianoRiccardo** [comment]
this still happens
