### ISSUE TITLE
db migration error from older sdk versions (0.18.0, 0.19.1, 0.20.0rc9) to 0.32.3

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-sdk#1966]
While this could be considered a rare edge case, it may occur for users with much older installs that need to upgrade to the latest sdk. @lyoshenka experienced this on mobile. The sdk log is pasted below.

 ```
2019-02-27 15:45:09,356 INFO     lbrynet.extras.daemon.Components:91: Loading databases
2019-02-27 15:45:09,363 INFO     lbrynet.extras.daemon.Components:107: Upgrading your databases (revision 7 to 9)
2019-02-27 15:45:09,366 INFO     lbrynet.extras.daemon.Components:577: detecting external ip
2019-02-27 15:45:09,378 WARNING  lbrynet.extras.daemon.Components:238: Moving old headers from /storage/emulated/0/Android/data/io.lbry.browser/files/lbryum/blockchain_headers to /storage/emulated/0/Android/data/io.lbry.browser/files/lbryum/lbc_mainnet/headers.
2019-02-27 15:45:09,417 INFO     lbrynet.extras.daemon.migrator.dbmigrator:30: successfully migrated the database from revision 7 to 8
2019-02-27 15:45:09,671 INFO     lbrynet.extras.daemon.exchange_rate_manager:211: Starting exchange rate manager
2019-02-27 15:45:09,678 ERROR    lbrynet.extras.daemon.Component:61: Error setting up database
Traceback (most recent call last):
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Component.py", line 55, in _setup
    result = await self.start()
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Components.py", line 109, in start
    None, dbmigrator.migrate_db, self.conf, old_revision, self.get_current_db_revision()
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/stdlib.zip/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/migrator/dbmigrator.py", line 28, in migrate_db
    do_migration(conf)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/migrator/migrate8to9.py", line 27, in do_migration
    sd = StreamDescriptor(asyncio.get_event_loop(), blob_dir, stream_name, stream_key, suggested_filename,
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/stdlib.zip/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
```

**Comment by akinwale** [comment]
Another error log migrating from 0.19.1 to 0.32.3 on desktop.
```
2019-02-24 12:00:54,007 INFO     lbrynet.extras.daemon.migrator.dbmigrator:30: successfully migrated the database from revision 6 to 7
2019-02-24 12:00:54,381 INFO     lbrynet.extras.daemon.migrator.dbmigrator:30: successfully migrated the database from revision 7 to 8
2019-02-24 12:00:54,858 INFO     lbrynet.extras.daemon.exchange_rate_manager:211: Starting exchange rate manager
2019-02-24 12:00:54,860 ERROR    lbrynet.extras.daemon.Component:61: Error setting up database
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 109, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 28, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate8to9.py", line 27, in do_migration
  File "asyncio\events.py", line 644, in get_event_loop
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
```

cc @tzarebczan

**Comment by tzarebczan** [comment]
this is the failure from 18.2, which is similar to https://github.com/lbryio/lbry/issues/1699
```2019-03-01 22:48:38,471 ERROR    lbrynet.extras.daemon.Component:61: Error setting up database
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 107, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 28, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate4to5.py", line 10, in do_migration
  File "lbrynet\extras\daemon\migrator\migrate4to5.py", line 28, in add_lbry_file_metadata
  File "logging\__init__.py", line 1412, in error
  File "logging\__init__.py", line 1519, in _log
  File "logging\__init__.py", line 1529, in handle
  File "logging\__init__.py", line 1591, in callHandlers
  File "logging\__init__.py", line 905, in handle
  File "lbrynet\extras\daemon\loggly_handler.py", line 57, in emit
  File "asyncio\tasks.py", line 580, in ensure_future
  File "asyncio\events.py", line 644, in get_event_loop
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
2019-03-01 22:48:39,016 INFO     torba.client.basenetwork:88: Successfully connected to SPV wallet server: lbryumx1.lbry.io:50001
2019-03-01 22:48:39,217 INFO     lbrynet.extras.daemon.Components:205: remote height: 527741, local height: 527844
2019-03-01 22:48:53,615 WARNING  lbrynet.extras.daemon.Components:511: upnp discovery failed: M-SEARCH for 172.16.1.254:1900 timed out
2019-03-01 22:48:53,616 WARNING  lbrynet.extras.daemon.Components:525: unable to get external ip from UPnP, checking lbry.io fallback
2019-03-01 22:48:54,410 ERROR    lbrynet.extras.daemon.Components:590: failed to setup upnp
Task exception was never retrieved
future: <Task finished coro=<Component._setup() done, defined at lbrynet\extras\daemon\Component.py:53> exception=RuntimeError("There is no current event loop in thread 'ThreadPoolExecutor-0_0'.")>
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 62, in _setup
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 107, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 28, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate4to5.py", line 10, in do_migration
  File "lbrynet\extras\daemon\migrator\migrate4to5.py", line 28, in add_lbry_file_metadata
  File "logging\__init__.py", line 1412, in error
  File "logging\__init__.py", line 1519, in _log
  File "logging\__init__.py", line 1529, in handle
  File "logging\__init__.py", line 1591, in callHandlers
  File "logging\__init__.py", line 905, in handle
  File "lbrynet\extras\daemon\loggly_handler.py", line 57, in emit
  File "asyncio\tasks.py", line 580, in ensure_future
  File "asyncio\events.py", line 644, in get_event_loop
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
C:\Users\SoloDolo\AppData\Local\Temp\_MEI281482\lbrynet\extras\daemon\ComponentManager.py:121: RuntimeWarning: coroutine 'HTTPSLogglyHandler._emit' was never awaited
2019-03-01 22:48:55,052 INFO     lbrynet.extras.daemon.Components:277: Starting torba wallet
2019-03-01 22:48:55,054 INFO     lbrynet.extras.wallet.manager:122: Wallet migrator found 20 receiving addresses and 6 change addresses. 26 in total on history.
2019-03-01 22:48:55,184 INFO     torba.client.basedatabase:186: connecting to database: c:\lbryupgrade1\lbc_mainnet\blockchain.db
2019-03-01 22:48:55,208 INFO     lbrynet.extras.daemon.Components:354: start the dht
2019-03-01 22:48:55,214 INFO     lbrynet.extras.daemon.Components:379: Started the dht
2019-03-01 22:48:55,217 ERROR    lbrynet.extras.daemon.Component:61: Error setting up blob_manager
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 310, in start
  File "lbrynet\blob\blob_manager.py", line 39, in setup
AttributeError: 'NoneType' object has no attribute 'sync_missing_blobs'
2019-03-01 22:48:55,228 INFO     lbrynet.dht.node:115: DHT node listening on UDP 0.0.0.0:4444
2019-03-01 22:48:55,349 INFO     lbrynet.extras.wallet.manager:209: Successfully migrated 6 change addresses.
2019-03-01 22:48:55,350 INFO     lbrynet.extras.wallet.manager:214: Successfully migrated 20 receiving addresses.
2019-03-01 22:48:55,360 INFO     torba.client.basedatabase:186: connecting to database: c:\lbryupgrade1\lbc_mainnet\blockchain.db
2019-03-01 22:48:55,786 INFO     torba.client.basenetwork:88: Successfully connected to SPV wallet server: lbryumx1.lbry.io:50001
2019-03-01 22:48:55,787 INFO     torba.client.baseledger:239: Subscribing and updating accounts.
Task exception was never retrieved
future: <Task finished coro=<Component._setup() done, defined at lbrynet\extras\daemon\Component.py:53> exception=AttributeError("'NoneType' object has no attribute 'sync_missing_blobs'")>
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 62, in _setup
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 310, in start
  File "lbrynet\blob\blob_manager.py", line 39, in setup```

**Comment by tzarebczan** [comment]
Yet another user ran into the migration issue:

```2019-03-16 11:10:39,533 ERROR    lbrynet.extras.daemon.Component:61: Error setting up blob_manager
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 310, in start
  File "lbrynet\blob\blob_manager.py", line 39, in setup
AttributeError: 'NoneType' object has no attribute 'sync_missing_blobs'
2019-03-16 11:10:39,671 INFO     torba.client.basenetwork:88: Successfully connected to SPV wallet server: lbryumx1.lbry.io:50001
2019-03-16 11:10:39,672 INFO     torba.client.baseledger:239: Subscribing and updating accounts.
2019-03-16 11:10:39,960 INFO     lbrynet.extras.wallet.ledger:101: Loaded account bJvLC2mJCrzyMvMGr7Gg9twoT1MouuyymH with 0.0 LBC, 22 receiving addresses (gap: 20), 7 change addresses (gap: 6), 0 channels, 0 certificates and 0 claims. 
2019-03-16 11:10:39,963 INFO     lbrynet.extras.daemon.Components:441: Starting the file manager
2019-03-16 11:10:39,964 ERROR    lbrynet.extras.daemon.Component:61: Error setting up stream_manager
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 446, in start
  File "lbrynet\stream\stream_manager.py", line 236, in start
  File "lbrynet\stream\stream_manager.py", line 182, in load_streams_from_database
AttributeError: 'NoneType' object has no attribute 'get_all_lbry_files'
2019-03-16 11:11:52,443 INFO     lbrynet.extras.daemon.Daemon:395: lbrynet API listening on TCP ::1:5279
2019-03-16 11:11:52,447 INFO     lbrynet.extras.daemon.Components:89: Loading databases
2019-03-16 11:11:52,450 INFO     lbrynet.extras.daemon.Components:105: Upgrading your databases (revision 4 to 9)

2019-03-16 11:11:52,940 ERROR    lbrynet.extras.daemon.Component:61: Error setting up database
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 107, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 28, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate4to5.py", line 10, in do_migration
  File "lbrynet\extras\daemon\migrator\migrate4to5.py", line 56, in add_lbry_file_metadata
sqlite3.IntegrityError: UNIQUE constraint failed: lbry_file_metadata.lbry_file```

**Comment by tzarebczan** [comment]
Started up an older 0.19 node and it also failed in a similar fashion:
```2019-04-16 12:10:10,284 ERROR    lbrynet.extras.daemon.Component:61: Error setting up database
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 97, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 28, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate8to9.py", line 27, in do_migration
  File "asyncio\events.py", line 644, in get_event_loop
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_1'.
2019-04-16 12:10:25,308 WARNING  lbrynet.extras.daemon.Components:501: upnp discovery failed: M-SEARCH for 10.1.10.1:1900 timed out
2019-04-16 12:10:25,310 WARNING  lbrynet.extras.daemon.Components:515: unable to get external ip from UPnP, checking lbry.io fallback
2019-04-16 12:10:25,470 ERROR    lbrynet.extras.daemon.Components:580: failed to setup upnp
2019-04-16 12:10:25,934 INFO     lbrynet.extras.daemon.Components:267: Starting torba wallet
2019-04-16 12:10:25,937 INFO     lbrynet.extras.wallet.manager:122: Wallet migrator found 226 receiving addresses and 95 change addresses. 321 in total on history.
2019-04-16 12:10:26,016 INFO     torba.client.basedatabase:186: connecting to database: C:\Users\User\AppData\Local\lbry\lbryum\lbc_mainnet\blockchain.db
2019-04-16 12:10:26,018 INFO     lbrynet.extras.daemon.Components:344: start the dht
2019-04-16 12:10:26,024 INFO     lbrynet.extras.daemon.Components:369: Started the dht
2019-04-16 12:10:26,026 INFO     lbrynet.dht.node:115: DHT node listening on UDP 0.0.0.0:4444
2019-04-16 12:10:26,043 ERROR    lbrynet.extras.daemon.Component:61: Error setting up blob_manager
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 300, in start
  File "lbrynet\blob\blob_manager.py", line 39, in setup
AttributeError: 'NoneType' object has no attribute 'sync_missing_blobs'```

**Comment by tzarebczan** [comment]
Here's another to 37.2 
```Daemon: 2019-06-09 07:04:37,997 INFO???????? lbrynet.extras.daemon.Components:94: Upgrading your databases (revision 6 to 11)

Daemon: 2019-06-09 07:04:38,153 INFO???????? lbrynet.extras.daemon.Components:563: detecting external ip

Daemon: 2019-06-09 07:04:38,153 INFO???????? lbrynet.extras.daemon.exchange_rate_manager:212: Starting exchange rate manager

Daemon: 2019-06-09 07:04:38,154 ERROR?????? lbrynet.extras.daemon.Component:61: Error setting up database
Traceback (most recent call last):
?? File "lbrynet/extras/daemon/Component.py", line 55, in _setup
?? File "lbrynet/extras/daemon/Components.py", line 96, in start
?? File "concurrent/futures/thread.py", line 57, in run
?? File "lbrynet/extras/daemon/migrator/dbmigrator.py", line 32, in migrate_db
?? File "lbrynet/extras/daemon/migrator/migrate6to7.py", line 9, in do_migration
sqlite3.OperationalError: duplicate column name: last_announced_time

Daemon: 2019-06-09 07:04:38,273 INFO???????? torba.client.basenetwork:88: Successfully connected to SPV wallet server: lbryumx1.lbry.com:50001

Daemon: 2019-06-09 07:04:38,321 INFO???????? lbrynet.extras.daemon.Components:194: remote height: 581439, local height: 581175

Daemon: 2019-06-09 07:04:53,198 WARNING?? lbrynet.extras.daemon.Components:499: upnp discovery failed: M-SEARCH for 192.168.2.1:1900 timed out

Daemon: 2019-06-09 07:04:53,199 WARNING?? lbrynet.extras.daemon.Components:513: unable to get external ip from UPnP, checking lbry.io fallback

Daemon: 2019-06-09 07:04:53,401 ERROR?????? lbrynet.extras.daemon.Components:578: failed to setup upnp

Daemon: Task exception was never retrieved
future: <Task finished coro=<Component._setup() done, defined at lbrynet/extras/daemon/Component.py:53> exception=OperationalError('duplicate column name: last_announced_time')>
Traceback (most recent call last):
?? File "lbrynet/extras/daemon/Component.py", line 62, in _setup
?? File "lbrynet/extras/daemon/Component.py", line 55, in _setup
?? File "lbrynet/extras/daemon/Components.py", line 96, in start
?? File "concurrent/futures/thread.py", line 57, in run
?? File "lbrynet/extras/daemon/migrator/dbmigrator.py", line 32, in migrate_db
?? File "lbrynet/extras/daemon/migrator/migrate6to7.py", line 9, in do_migration
sqlite3.OperationalError: duplicate column name: last_announced_time

Daemon: 2019-06-09 07:04:53,843 INFO???????? lbrynet.extras.daemon.Components:266: Starting torba wallet

Daemon: 2019-06-09 07:04:53,843 ERROR?????? lbrynet.extras.daemon.Component:61: Error setting up wallet
Traceback (most recent call last):
?? File "lbrynet/extras/daemon/Component.py", line 55, in _setup
?? File "lbrynet/extras/daemon/Components.py", line 267, in start
?? File "lbrynet/wallet/manager.py", line 145, in from_lbrynet_config
?? File "lbrynet/wallet/manager.py", line 72, in migrate_lbryum_to_torba
PermissionError: [Errno 13] Permission denied: '/home/adminles/.local/share/lbry/lbryum/wallets/default_wallet'

Daemon: 2019-06-09 07:04:53,844 INFO???????? lbrynet.extras.daemon.Components:342: start the dht

Daemon: 2019-06-09 07:04:53,845 INFO???????? lbrynet.extras.daemon.Components:367: Started the dht

Daemon: 2019-06-09 07:04:53,850 ERROR?????? lbrynet.extras.daemon.Component:61: Error setting up blob_manager
Traceback (most recent call last):
?? File "lbrynet/extras/daemon/Component.py", line 55, in _setup
?? File "lbrynet/extras/daemon/Components.py", line 298, in start
?? File "lbrynet/blob/blob_manager.py", line 84, in setup
AttributeError: 'NoneType' object has no attribute 'sync_missing_blobs'

Daemon: 2019-06-09 07:04:53,850 INFO???????? lbrynet.dht.node:118: DHT node listening on UDP 0.0.0.0:44444

Daemon: Task exception was never retrieved
future: <Task finished coro=<Component._setup() done, defined at lbrynet/extras/daemon/Component.py:53> exception=AttributeError("'NoneType' object has no attribute 'sync_missing_blobs'")>
Traceback (most recent call last):
?? File "lbrynet/extras/daemon/Component.py", line 62, in _setup
?? File "lbrynet/extras/daemon/Component.py", line 55, in _setup
?? File "lbrynet/extras/daemon/Components.py", line 298, in start
?? File "lbrynet/blob/blob_manager.py", line 84, in setup
AttributeError: 'NoneType' object has no attribute 'sync_missing_blobs'

Daemon: Task exception was never retrieved
future: <Task finished coro=<Component._setup() done, defined at lbrynet/extras/daemon/Component.py:53> exception=PermissionError(13, 'Permission denied')>
Traceback (most recent call last):
?? File "lbrynet/extras/daemon/Component.py", line 62, in _setup
?? File "lbrynet/extras/daemon/Component.py", line 55, in _setup
?? File "lbrynet/extras/daemon/Components.py", line 267, in start
?? File "lbrynet/wallet/manager.py", line 145, in from_lbrynet_config
?? File "lbrynet/wallet/manager.py", line 72, in migrate_lbryum_to_torba
PermissionError: [Errno 13] Permission denied: '/home/adminles/.local/share/lbry/lbryum/wallets/default_wallet'

Daemon: 2019-06-09 07:04:53,856 INFO???????? lbrynet.extras.daemon.Components:454: start blob server

Daemon: 2019-06-09 07:04:53,857 ERROR?????? lbrynet.extras.daemon.Component:61: Error setting up peer_protocol_server
Traceback (most recent call last):
?? File "lbrynet/extras/daemon/Component.py", line 55, in _setup
?? File "lbrynet/extras/daemon/Components.py", line 459, in start
AttributeError: 'NoneType' object has no attribute 'get_unused_address'

Daemon: 2019-06-09 07:04:53,857 INFO???????? lbrynet.extras.daemon.Components:390: Started blob announcer

Daemon: 2019-06-09 07:04:53,858 INFO???????? lbrynet.extras.daemon.Components:429: Starting the file manager

Daemon: 2019-06-09 07:04:53,858 ERROR?????? lbrynet.extras.daemon.Component:61: Error setting up stream_manager
Traceback (most recent call last):
?? File "lbrynet/extras/daemon/Component.py", line 55, in _setup
?? File "lbrynet/extras/daemon/Components.py", line 434, in start
?? File "lbrynet/stream/stream_manager.py", line 196, in start
?? File "lbrynet/stream/stream_manager.py", line 135, in load_and_resume_streams_from_database
AttributeError: 'NoneType' object has no attribute 'update_manually_removed_files_since_last_run'

Daemon: Task exception was never retrieved
future: <Task finished coro=<Component._setup() done, defined at lbrynet/extras/daemon/Component.py:53> exception=AttributeError("'NoneType' object has no attribute 'update_manually_removed_files_since_last_run'")>
Traceback (most recent call last):
?? File "lbrynet/extras/daemon/Component.py", line 62, in _setup
?? File "lbrynet/extras/daemon/Component.py", line 55, in _setup
?? File "lbrynet/extras/daemon/Components.py", line 434, in start
?? File "lbrynet/stream/stream_manager.py", line 196, in start
?? File "lbrynet/stream/stream_manager.py", line 135, in load_and_resume_streams_from_database
AttributeError: 'NoneType' object has no attribute 'update_manually_removed_files_since_last_run'

Daemon: Task exception was never retrieved
future: <Task finished coro=<Component._setup() done, defined at lbrynet/extras/daemon/Component.py:53> exception=AttributeError("'NoneType' object has no attribute 'get_unused_address'")>
Traceback (most recent call last):
?? File "lbrynet/extras/daemon/Component.py", line 62, in _setup
?? File "lbrynet/extras/daemon/Component.py", line 55, in _setup
?? File "lbrynet/extras/daemon/Components.py", line 459, in start```

**Comment by tzarebczan** [comment]
Another: ```
2019-06-10 18:55:20,219 INFO     lbrynet.extras.daemon.Components:78: Loading databases
2019-06-10 18:55:20,236 INFO     lbrynet.extras.daemon.Components:94: Upgrading your databases (revision 6 to 11)
2019-06-10 18:55:20,364 INFO     lbrynet.extras.daemon.Components:497: found upnp gateway: MiniUPnP WAN Device
2019-06-10 18:55:20,369 INFO     lbrynet.extras.daemon.Components:508: got external ip from UPnP: 124.171.188.93
2019-06-10 18:55:20,369 INFO     lbrynet.extras.daemon.Components:522: add UPnP port mappings
2019-06-10 18:55:20,537 INFO     lbrynet.extras.daemon.Components:529: set up redirects: {'TCP': 3333, 'UDP': 4444}
2019-06-10 18:55:20,764 INFO     lbrynet.extras.daemon.migrator.dbmigrator:34: successfully migrated the database from revision 6 to 7
2019-06-10 18:55:20,883 INFO     torba.client.basenetwork:88: Successfully connected to SPV wallet server: lbryumx1.lbry.com:50001
2019-06-10 18:55:20,961 INFO     lbrynet.extras.daemon.migrator.dbmigrator:34: successfully migrated the database from revision 7 to 8
2019-06-10 18:55:21,113 ERROR    lbrynet.extras.daemon.Component:61: Error setting up database
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 96, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 32, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate8to9.py", line 27, in do_migration
  File "asyncio\events.py", line 644, in get_event_loop
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_4'.
```

**Comment by tzarebczan** [comment]
Another upgrade failure from a really old version: ```rate manager
2019-06-18 20:12:24,981 INFO     lbrynet.extras.daemon.Components:78: Loading databases
2019-06-18 20:12:24,983 INFO     lbrynet.extras.daemon.Components:94: Upgrading your databases (revision 3 to 11)
2019-06-18 20:12:24,983 INFO     lbrynet.extras.daemon.migrator.migrate3to4:9: Doing the migration
2019-06-18 20:12:25,134 ERROR    lbrynet.extras.daemon.migrator.migrate3to4:81: Some how not all blobs were marked as announceable
2019-06-18 20:12:25,134 ERROR    lbrynet.extras.daemon.Component:61: Error setting up database
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 96, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 32, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate3to4.py", line 10, in do_migration
  File "lbrynet\extras\daemon\migrator\migrate3to4.py", line 81, in migrate_blobs_db
  File "logging\__init__.py", line 1412, in error
  File "logging\__init__.py", line 1519, in _log
  File "logging\__init__.py", line 1529, in handle
  File "logging\__init__.py", line 1591, in callHandlers
  File "logging\__init__.py", line 905, in handle
  File "lbrynet\extras\daemon\loggly_handler.py", line 57, in emit
  File "asyncio\tasks.py", line 580, in ensure_future
  File "asyncio\events.py", line 644, in get_event_loop
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
2019-06-18 20:12:25,170 INFO     lbrynet.extras.daemon.Daemon:815: Get version info: {"processor": "AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD", "python_version": "3.7.1", "platform": "Windows-10-10.0.17134", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.37.4", "torba_version": "0.5.4a0", "build": "release"}```

**Comment by tzarebczan** [comment]
These migration errors should be handled by https://github.com/lbryio/lbry-sdk/pull/2267 which pretty much resets their db (and they lose any old data), but we still don't know what was causing them and if any are recoverable.

**Comment by tzarebczan** [comment]
Here's a recent one that didn't convert automatically. @jackrobison  any ideas ? 
```
019-11-16 12:04:53,175 INFO     lbry.extras.daemon.Daemon:402: Starting LBRYNet Daemon
2019-11-16 12:04:53,176 INFO     lbry.extras.daemon.Daemon:404: Platform: {
  "processor": "Intel64 Family 6 Model 58 Stepping 9, GenuineIntel",
  "python_version": "3.7.4",
  "platform": "Windows-10-10.0.18362-SP0",
  "os_release": "10",
  "os_system": "Windows",
  "lbrynet_version": "0.43.3",
  "torba_version": "0.5.7",
  "build": "release"
}
2019-11-16 12:04:58,497 INFO     lbry.extras.daemon.Daemon:412: RPC server listening on TCP 127.0.0.1:5279
2019-11-16 12:04:58,500 INFO     lbry.extras.daemon.Daemon:422: media server listening on TCP 127.0.0.1:5280
2019-11-16 12:04:58,685 INFO     lbry.extras.daemon.Daemon:388: detected internet connection is working
2019-11-16 12:04:58,848 INFO     lbry.extras.daemon.Daemon:821: Get version info: {"processor": "Intel64 Family 6 Model 58 Stepping 9, GenuineIntel", "python_version": "3.7.4", "platform": "Windows-10-10.0.18362-SP0", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.43.3", "torba_version": "0.5.7", "build": "release"}
2019-11-16 12:04:59,003 INFO     lbry.extras.daemon.exchange_rate_manager:213: Starting exchange rate manager
2019-11-16 12:04:59,004 INFO     lbry.extras.daemon.Components:564: detecting external ip
2019-11-16 12:04:59,280 INFO     lbry.extras.daemon.Components:67: Loading databases
2019-11-16 12:04:59,286 INFO     lbry.extras.daemon.Components:83: Upgrading your databases (revision 6 to 11)
2019-11-16 12:04:59,326 WARNING  lbry.extras.daemon.Components:202: Moving old headers from C:\Users\Buddy\AppData\Local\lbry\lbryum\blockchain_headers to C:\Users\Buddy\AppData\Local\lbry\lbryum\lbc_mainnet\headers.
2019-11-16 12:04:59,348 INFO     lbry.extras.daemon.Daemon:821: Get version info: {"processor": "Intel64 Family 6 Model 58 Stepping 9, GenuineIntel", "python_version": "3.7.4", "platform": "Windows-10-10.0.18362-SP0", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.43.3", "torba_version": "0.5.7", "build": "release"}
2019-11-16 12:04:59,603 INFO     lbry.extras.daemon.Components:180: remote height: 664762, local height: 385488
2019-11-16 12:04:59,882 INFO     lbry.extras.daemon.Components:149: Resuming download of 31278688 bytes from s3
2019-11-16 12:05:00,747 INFO     lbry.extras.daemon.migrator.dbmigrator:51: successfully migrated the database from revision 6 to 7
2019-11-16 12:05:01,106 INFO     lbry.extras.daemon.migrator.dbmigrator:51: successfully migrated the database from revision 7 to 8
2019-11-16 12:05:01,303 INFO     lbry.extras.daemon.migrator.migrate8to9:29: Stream for descriptor fb1d3533a2ddd094762b81e9e94fd852794c666ee84b435189aed8ae831c0a9aa7e8b81b1644974703f010a41323587a is invalid, cleaning it up
2019-11-16 12:05:03,743 INFO     lbry.extras.daemon.migrator.dbmigrator:37: failed to migrate database: join() argument must be str or bytes, not 'NoneType'
2019-11-16 12:05:03,744 ERROR    lbry.extras.daemon.Component:62: Error setting up database
Traceback (most recent call last):
  File "lbry\extras\daemon\migrator\dbmigrator.py", line 35, in migrate_db
  File "lbry\extras\daemon\migrator\migrate8to9.py", line 31, in do_migration
  File "lbry\extras\daemon\migrator\migrate8to9.py", line 45, in delete_stream
  File "ntpath.py", line 115, in join
  File "genericpath.py", line 149, in _check_arg_types
TypeError: join() argument must be str or bytes, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lbry\extras\daemon\Component.py", line 55, in _setup
  File "lbry\extras\daemon\Components.py", line 85, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbry\extras\daemon\migrator\dbmigrator.py", line 45, in migrate_db
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Buddy\\AppData\\Local\\lbry\\lbrynet\\lbrynet.sqlite' -> 'C:\\Users\\Buddy\\AppData\\Local\\lbry\\lbrynet\\rev_8_unmigrated_database.sqlite'
2019-11-16 12:05:14,283 WARNING  lbry.extras.daemon.Components:493: upnp discovery failed: M-SEARCH for 192.168.0.1:1900 timed out
2019-11-16 12:05:14,283 ERROR    lbry.extras.daemon.Components:579: failed to setup upnp
2019-11-16 12:05:20,133 INFO     lbry.extras.daemon.Components:220: Header checkpoint verified.
2019-11-16 12:05:20,140 INFO     lbry.extras.daemon.Components:336: start the dht
2019-11-16 12:05:20,141 WARNING  lbry.extras.daemon.Components:342: UPnP component failed to get external ip
2019-11-16 12:05:20,142 INFO     lbry.extras.daemon.Components:258: Starting torba wallet
2019-11-16 12:05:20,160 INFO     lbry.wallet.manager:52: Wallet migrator found 20 receiving addresses and 6 change addresses. 26 in total on history.
2019-11-16 12:05:20,431 INFO     torba.client.basedatabase:233: connecting to database: C:\Users\Buddy\AppData\Local\lbry\lbryum\lbc_mainnet\blockchain.db
2019-11-16 12:05:20,434 ERROR    lbry.extras.daemon.Component:62: Error setting up blob_manager
Traceback (most recent call last):
  File "lbry\extras\daemon\Component.py", line 55, in _setup
  File "lbry\extras\daemon\Components.py", line 290, in start
  File "lbry\blob\blob_manager.py", line 83, in setup
AttributeError: 'NoneType' object has no attribute 'sync_missing_blobs'
2019-11-16 12:05:20,835 INFO     lbry.extras.daemon.Components:361: Starte```

**Comment by lyoshenka** [comment]
closing this. not gonna spend more time on these old versions
