### ISSUE TITLE
subsequent transactions from multisig address fail to sync / show in history

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2074]
## The Issue
Once you receive a single tx from a multisig address, subsequent transactions will not show up in your history until the sdk is restarted. This applies to any wallet address it's sent to, not only the original one that was sent. 
```
019-05-01 13:00:21,905 INFO     lbrynet.dht.node:162: Joined DHT, 16 peers known in 3 buckets
2019-05-01 13:01:46,137 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560471, change=1) header blocks, final height 560471
2019-05-01 13:02:21,180 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560472, change=1) header blocks, final height 560472
2019-05-01 13:04:06,374 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bZtnbpmPPEp2Sy4RCWXpdP6Xw9qQWLYkxa, height=0, is_verified=False, tx.id=0fc16c48efcd919488614dd7a8dde5f0516603f7181bd2331eb4f704d4ddf0ed
2019-05-01 13:04:06,431 INFO     torba.client.baseledger:125: (lbc_mainnet) on_address: ['bMhEh7dT5M2TbcxwpHVnacz27UwnjVVycH', 'bTYWV8bY5LCSTtYvNbPhPwMqezAox1UsEk', 'bZT72Jt8LpZ377acgPHx4Mmk7dmgKpGvAB', 'bUkaP2jAKGTi9p1AUitQczn4Dm7MGPAHeA', 'bG64j7PMAnZxQDimR7THch7BoSHL5y5xuZ']
2019-05-01 13:05:16,397 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560473, change=1) header blocks, final height 560473
2019-05-01 13:05:16,459 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bZtnbpmPPEp2Sy4RCWXpdP6Xw9qQWLYkxa, height=560473, is_verified=True, tx.id=0fc16c48efcd919488614dd7a8dde5f0516603f7181bd2331eb4f704d4ddf0ed
2019-05-01 13:06:02,348 INFO     lbrynet.extras.daemon.Daemon:729: Get version info: {"processor": "AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD", "python_version": "3.7.1", "platform": "Windows-10-10.0.16299", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.34.0", "lbryschema_version": "0.0.16", "build": "release"}
2019-05-01 13:06:36,631 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bZtnbpmPPEp2Sy4RCWXpdP6Xw9qQWLYkxa, height=0, is_verified=False, tx.id=c9281817ed04c1dea53298221e85421e8e65f08de537237ff9cafad61ddad6fe
2019-05-01 13:09:26,912 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560474, change=1) header blocks, final height 560474
2019-05-01 13:09:26,976 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bZtnbpmPPEp2Sy4RCWXpdP6Xw9qQWLYkxa, height=560474, is_verified=True, tx.id=c9281817ed04c1dea53298221e85421e8e65f08de537237ff9cafad61ddad6fe
2019-05-01 13:15:12,538 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560475, change=1) header blocks, final height 560475
2019-05-01 13:15:34,913 WARNING  lbrynet.dht.protocol.protocol:492: known dht protocol backwards compatibility error with 199.115.205.245:4444 (lbrynet v0.19.1)
2019-05-01 13:15:52,600 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560476, change=1) header blocks, final height 560476
2019-05-01 13:16:17,631 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560477, change=1) header blocks, final height 560477
2019-05-01 13:19:33,037 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bZtnbpmPPEp2Sy4RCWXpdP6Xw9qQWLYkxa, height=0, is_verified=False, tx.id=1f39d4292d501484eaa748412073b9e08572d878447811ce7066c1c5384dc45e
2019-05-01 13:19:53,070 WARNING  torba.client.basedatabase:326: Database.save_transaction_io: pay script hash is not implemented!
2019-05-01 13:19:53,084 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bJWEsQj454ResPExpZoi6nuomBBKhUD6ea, height=0, is_verified=False, tx.id=f388ce5473d0d005880190e57400ecd2fe5fa615feddd6080669218d82b1db31
2019-05-01 13:21:23,147 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560478, change=1) header blocks, final height 560478
2019-05-01 13:21:23,241 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bZtnbpmPPEp2Sy4RCWXpdP6Xw9qQWLYkxa, height=560478, is_verified=True, tx.id=1f39d4292d501484eaa748412073b9e08572d878447811ce7066c1c5384dc45e
2019-05-01 13:21:23,256 WARNING  torba.client.basedatabase:326: Database.save_transaction_io: pay script hash is not implemented!
2019-05-01 13:21:23,256 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bJWEsQj454ResPExpZoi6nuomBBKhUD6ea, height=560478, is_verified=True, tx.id=f388ce5473d0d005880190e57400ecd2fe5fa615feddd6080669218d82b1db31
2019-05-01 13:22:03,210 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560479, change=1) header blocks, final height 560479
2019-05-01 13:22:08,209 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560480, change=1) header blocks, final height 560480
2019-05-01 13:23:33,350 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560481, change=1) header blocks, final height 560481
2019-05-01 13:29:43,975 WARNING  torba.client.basedatabase:326: Database.save_transaction_io: pay script hash is not implemented!
2019-05-01 13:30:10,606 INFO     lbrynet.extras.daemon.Daemon:729: Get version info: {"processor": "AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD", "python_version": "3.7.1", "platform": "Windows-10-10.0.16299", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.34.0", "lbryschema_version": "0.0.16", "build": "release"}
2019-05-01 13:30:54,069 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560482, change=1) header blocks, final height 560482
2019-05-01 13:30:54,131 WARNING  torba.client.basedatabase:326: Database.save_transaction_io: pay script hash is not implemented!
2019-05-01 13:32:19,209 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=560483, change=1) header blocks, final height 560483
2019-05-01 13:33:05,975 INFO     lbrynet.extras.daemon.Daemon:612: Shutting down lbrynet daemon
2019-05-01 13:33:05,975 INFO     lbrynet.extras.daemon.Components:396: Stopped blob announcer
2019-05-01 13:33:05,975 INFO     lbrynet.blob_exchange.server:125: Stopped blob server
2019-05-01 13:33:05,975 INFO     lbrynet.dht.node:108: Stopped DHT node
2019-05-01 13:33:05,992 INFO     lbrynet.extras.daemon.exchange_rate_manager:216: Stopping exchange rate manager
2019-05-01 13:33:12,954 INFO     lbrynet.extras.daemon.Daemon:388: Starting LBRYNet Daemon
2019-05-01 13:33:12,954 INFO     lbrynet.extras.daemon.Daemon:390: Platform: {
  "processor": "AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD",
  "python_version": "3.7.1",
  "platform": "Windows-10-10.0.16299",
  "os_release": "10",
  "os_system": "Windows",
  "lbrynet_version": "0.34.0",
  "lbryschema_version": "0.0.16",
  "build": "release"
}
2019-05-01 13:33:13,375 INFO     lbrynet.extras.daemon.Daemon:397: lbrynet API listening on TCP 127.0.0.1:5279
2019-05-01 13:33:13,716 INFO     lbrynet.extras.daemon.exchange_rate_manager:211: Starting exchange rate manager
2019-05-01 13:33:13,717 INFO     lbrynet.extras.daemon.Components:79: Loading databases
2019-05-01 13:33:13,718 INFO     torba.client.basedatabase:186: connecting to database: C:\Users\tom\AppData\Local\lbry\lbrynet\lbrynet.sqlite
2019-05-01 13:33:13,719 INFO     lbrynet.extras.daemon.Components:565: detecting external ip
2019-05-01 13:33:13,785 INFO     lbrynet.extras.daemon.Components:499: found upnp gateway: NETGEAR NETGEAR Nighthawk X4 AC2350 Smart WiFi Router
2019-05-01 13:33:13,790 INFO     lbrynet.extras.daemon.Components:510: got external ip from UPnP: 24.184.108.248
2019-05-01 13:33:13,791 INFO     lbrynet.extras.daemon.Components:524: add UPnP port mappings
2019-05-01 13:33:13,808 INFO     lbrynet.extras.daemon.Daemon:729: Get version info: {"processor": "AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD", "python_version": "3.7.1", "platform": "Windows-10-10.0.16299", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.34.0", "lbryschema_version": "0.0.16", "build": "release"}
2019-05-01 13:33:13,826 INFO     torba.client.basenetwork:88: Successfully connected to SPV wallet server: victor.lbry.tech:50001
2019-05-01 13:33:13,846 INFO     lbrynet.extras.daemon.Components:195: remote height: 560483, local height: 560483
2019-05-01 13:33:13,891 INFO     lbrynet.extras.daemon.Daemon:729: Get version info: {"processor": "AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD", "python_version": "3.7.1", "platform": "Windows-10-10.0.16299", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.34.0", "lbryschema_version": "0.0.16", "build": "release"}
2019-05-01 13:33:14,225 INFO     lbrynet.extras.daemon.Components:531: set up redirects: {'TCP': 3334, 'UDP': 4445}
2019-05-01 13:33:14,612 INFO     lbrynet.extras.daemon.Components:267: Starting torba wallet
2019-05-01 13:33:14,679 INFO     lbrynet.extras.daemon.Components:344: start the dht
2019-05-01 13:33:14,682 INFO     lbrynet.extras.daemon.Components:369: Started the dht
2019-05-01 13:33:14,685 INFO     torba.client.basedatabase:186: connecting to database: C:\Users\tom\AppData\Local\lbry\lbryum\lbc_mainnet\blockchain.db
2019-05-01 13:33:14,687 INFO     lbrynet.dht.node:115: DHT node listening on UDP 0.0.0.0:4444
2019-05-01 13:33:14,763 INFO     torba.client.basenetwork:88: Successfully connected to SPV wallet server: victor.lbry.tech:50001
2019-05-01 13:33:14,764 INFO     torba.client.baseledger:239: Subscribing and updating accounts.
2019-05-01 13:33:14,899 WARNING  torba.client.basedatabase:326: Database.save_transaction_io: pay script hash is not implemented!
2019-05-01 13:33:14,915 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bJWEsQj454ResPExpZoi6nuomBBKhUD6ea, height=560482, is_verified=True, tx.id=3e95223bc8e1d7fd2486e19d3c045b5d80f9cc109f56f8f1772e53ac390884c2
2019-05-01 13:33:14,927 INFO     lbrynet.extras.wallet.ledger:101: Loaded account bQaPWKX4Rfg7kfaa4uvELtmvW4tVhvU2cs with 2.8 LBC, 25 receiving addresses (gap: 20), 6 change addresses (gap: 6), 0 channels, 0 certificates and 0 claims. 
2019-05-01 13:33:14,927 INFO     lbrynet.extras.daemon.Components:431: Starting the file manager
```
## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
We are using multisig wallets as part of the hive program, and these users send funds to their app often. This results in many issues including not showing their claims and transaction history (tips too). How much effort is it to support this?

**Comment by tzarebczan** [comment]
```2019-10-21 21:24:23,668 WARNING  torba.client.basedatabase:396: Database.save_transaction_io: pay script hash is not implemented!
2019-10-21 21:24:23,670 WARNING  torba.client.basedatabase:396: Database.save_transaction_io: pay script hash is not implemented!
2019-10-21 21:24:23,672 ERROR    torba.client.basedatabase:72: Error running transaction:
Traceback (most recent call last):
  File "torba\client\basedatabase.py", line 68, in __run_transaction
  File "torba\client\basedatabase.py", line 419, in __many
  File "torba\client\basedatabase.py", line 401, in _transaction_io
  File "torba\client\basetransaction.py", line 230, in get_address
  File "torba\client\basetransaction.py", line 227, in pubkey_hash
KeyError: 'pubkey_hash'
2019-10-21 21:24:23,675 WARNING  torba.client.basedatabase:74: rolled back```

**Comment by tzarebczan** [comment]
This is fixed now.
