### ISSUE TITLE
lbrynet.wallet.resolve:42: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2152]
## The Issue
Not sure why this is happening yet, and it's unclear if it's affecting anything, but I've run into this during an existing SDK session. Niko has seen this also, and I've seen it in other users' log files. Might be something with an unstable connection. 

```2019-05-16 15:39:56,726 ERROR    lbrynet.wallet.resolve:42: unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "lbrynet/wallet/resolve.py", line 38, in resolve
  File "lbrynet/wallet/resolve.py", line 67, in _handle_resolutions
  File "lbrynet/wallet/resolve.py", line 93, in _handle_resolve_uri_response
  File "lbrynet/wallet/resolve.py", line 156, in parse_and_validate_claim_result
  File "site-packages/torba/client/baseheader.py", line 74, in __getitem__
  File "lbrynet/wallet/header.py", line 35, in deserialize
struct.error: unpack requires a buffer of 4 bytes
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This is also happening during a stream update, when validating the channel cert, and it fails to actually update the stream. 

```
2019-05-31 22:28:19,687 INFO     lbrynet.wallet.resolve:163: fetching certificate to check claim signature
2019-05-31 22:28:19,729 ERROR    lbrynet.wallet.resolve:41: unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "lbrynet/wallet/resolve.py", line 37, in resolve
  File "lbrynet/wallet/resolve.py", line 64, in _handle_resolutions
  File "lbrynet/wallet/resolve.py", line 90, in _handle_resolve_uri_response
  File "lbrynet/wallet/resolve.py", line 153, in parse_and_validate_claim_result
  File "site-packages/torba/client/baseheader.py", line 74, in __getitem__
  File "lbrynet/wallet/header.py", line 35, in deserialize
struct.error: unpack requires a buffer of 4 bytes
2019-05-31 22:28:19,729 ERROR    lbrynet.extras.daemon.Daemon:576: error handling api request
Traceback (most recent call last):
  File "lbrynet/extras/daemon/Daemon.py", line 570, in _process_rpc_call
  File "lbrynet/extras/daemon/Daemon.py", line 1737, in jsonrpc_claim_search
  File "lbrynet/extras/daemon/Daemon.py", line 1737, in <listcomp>
AttributeError: 'str' object has no attribute 'get'```

**Comment by tzarebczan** [comment]
This is still happening on 0.38, not sure of the scenario or what trouble it causes. Will keep an eye out. 

```019-07-26 10:38:18,833 INFO     lbry.dht.node:92: Stored e08d5adf to 8 of 8 attempted peers
2019-07-26 10:38:21,004 INFO     lbry.dht.node:92: Stored 839c52b7 to 7 of 8 attempted peers
2019-07-26 10:38:23,629 INFO     lbry.dht.node:92: Stored 48a4a207 to 8 of 8 attempted peers
2019-07-26 10:38:23,892 INFO     lbry.dht.node:92: Stored 575b6fe3 to 8 of 8 attempted peers
2019-07-26 10:38:23,896 INFO     lbry.dht.node:92: Stored 548ebb64 to 8 of 8 attempted peers
2019-07-26 10:38:26,594 INFO     lbry.dht.node:92: Stored 35d89967 to 8 of 8 attempted peers
2019-07-26 10:38:26,597 INFO     lbry.dht.blob_announcer:51: announced 10 blobs
2019-07-26 10:39:26,602 INFO     lbry.dht.blob_announcer:43: 100 blobs to announce
2019-07-26 10:39:34,331 INFO     lbry.dht.node:92: Stored a95dc247 to 8 of 8 attempted peers
2019-07-26 10:39:36,120 ERROR    lbry.extras.daemon.Daemon:586: error handling api request
Traceback (most recent call last):
  File "lbry\extras\daemon\Daemon.py", line 580, in _process_rpc_call
  File "lbry\extras\daemon\Daemon.py", line 1835, in jsonrpc_claim_search
  File "lbry\wallet\ledger.py", line 78, in claim_search
  File "lbry\wallet\ledger.py", line 60, in _inflate_outputs
  File "torba\client\baseledger.py", line 472, in cache_transaction
  File "torba\client\baseledger.py", line 492, in maybe_verify_transaction
  File "torba\client\baseheader.py", line 75, in __getitem__
  File "lbry\wallet\header.py", line 35, in deserialize
struct.error: unpack requires a buffer of 4 bytes
2019-07-26 10:39:36,798 INFO     lbry.dht.node:92: Stored d8a4f00d to 8 of 8 attempted peers
2019-07-26 10:39:36,901 INFO     lbry.dht.node:92: Stored efd2e182 to 8 of 8 attempted peers
2019-07-26 10:39:37,946 INFO     torba.client.baseledger:134: lbc_mainnet: added BlockHeightEvent(height=606622, change=1) header blocks, final height 606622
2019-07-26 10:39:39,285 INFO     lbry.dht.node:92: Stored f73c1c1f to 8 of 8 attempted peers
2019-07-26 10:39:41,867 INFO     lbry.dht.node:92: Stored 41964438 to 8 of 8 attempted peers
2019-07-26 10:39:42,012 INFO     lbry.dht.node:92: Stored 6b8876d3 to 8 of 8 attempted peers
2019-07-26 10:39:46,758 INFO     lbry.dht.node:92: Stored 792a48ee to 7 of 8 attempted peers```

**Comment by jackrobison** [comment]
Slightly different traceback from 0.38.5 showing the same error: 
```
Traceback (most recent call last):
  File "lbry\extras\daemon\Daemon.py", line 482, in handle_old_jsonrpc
  File "lbry\extras\daemon\Daemon.py", line 235, in jsonrpc_dumps_pretty
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 201, in encode
  File "json\encoder.py", line 431, in _iterencode
  File "json\encoder.py", line 405, in _iterencode_dict
  File "json\encoder.py", line 405, in _iterencode_dict
  File "json\encoder.py", line 325, in _iterencode_list
  File "json\encoder.py", line 438, in _iterencode
  File "lbry\extras\daemon\json_response_encoder.py", line 118, in default
  File "lbry\extras\daemon\json_response_encoder.py", line 151, in encode_output
  File "torba\client\baseheader.py", line 75, in __getitem__
  File "lbry\wallet\header.py", line 35, in deserialize
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by tzarebczan** [comment]
Sounds like it's related to validating results against local headers. When I ran into this recently, I was able to do a claim search on trending data, but another claim search on a channel id would fail consistently.

**Comment by tzarebczan** [comment]
We found that this occurs when the client gets out of sync on headers with the server. Related to https://github.com/lbryio/lbry-sdk/issues/2392
