### ISSUE TITLE
lbry fails to start after adding single key account

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2160]
## The Issue

create a single key account and then restart: 
```
2019-05-22 09:03:08,312 ERROR    lbrynet.extras.daemon.Component:61: Error setting up wallet
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 268, in start
  File "torba\client\basemanager.py", line 73, in start
  File "lbrynet\wallet\ledger.py", line 70, in start
  File "lbrynet\wallet\ledger.py", line 81, in _report_state
AttributeError: 'SingleKey' object has no attribute 'gap'
Task exception was never retrieved
future: <Task finished coro=<Component._setup() done, defined at lbrynet\extras\daemon\Component.py:53> exception=AttributeError("'SingleKey' object has no attribute 'gap'")>
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 62, in _setup
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 268, in start
  File "torba\client\basemanager.py", line 73, in start
  File "lbrynet\wallet\ledger.py", line 70, in start
  File "lbrynet\wallet\ledger.py", line 81, in _report_state
AttributeError: 'SingleKey' object has no attribute 'gap'
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
fixed in #2167
