### ISSUE TITLE
Fix integration tests so they don't fail randomly and we can trust them

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2221]

**Comment by osilkin98** [comment]
A `retry` button would be nice. Alternatively I was thinking of setting up a dedicated AWS instance for running travis builds and tests so that way we can have more fine-grained control over the environment

**Comment by lyoshenka** [comment]
Niko already has a gitlab ci server up and running. Consider trying that
first before doing something custom.

**Comment by eukreign** [comment]
```
======================================================================
142 ERROR: test_null_max_key_fee (integration.datanetwork.test_file_commands.FileCommands)
143 ----------------------------------------------------------------------
144 Traceback (most recent call last):
145   File "/builds/lbry/lbry-sdk/.tox/datanetwork/lib/python3.7/site-packages/lbry/testcase.py", line 139, in run
146     self.loop.run_until_complete(maybe_coroutine)
147   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
148     return future.result()
149   File "/builds/lbry/lbry-sdk/tests/integration/datanetwork/test_file_commands.py", line 381, in test_null_max_key_fee
150     await self.ledger.wait(response.content_fee)
151   File "/builds/lbry/lbry-sdk/.tox/datanetwork/lib/python3.7/site-packages/lbry/wallet/ledger.py", line 621, in wait
152     _, local_history = await self.get_local_status_and_history(None, history=record['history'])
153   File "/builds/lbry/lbry-sdk/.tox/datanetwork/lib/python3.7/site-packages/lbry/wallet/ledger.py", line 274, in get_local_status_and_history
154     history = address_details['history'] or ''
155 TypeError: 'NoneType' object is not subscriptable
156 ======================================================================
157 ERROR: test_paid_download (integration.datanetwork.test_file_commands.FileCommands)
158 ----------------------------------------------------------------------
159 Traceback (most recent call last):
160   File "/builds/lbry/lbry-sdk/.tox/datanetwork/lib/python3.7/site-packages/lbry/testcase.py", line 139, in run
161     self.loop.run_until_complete(maybe_coroutine)
162   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
163     return future.result()
164   File "/builds/lbry/lbry-sdk/tests/integration/datanetwork/test_file_commands.py", line 330, in test_paid_download
165     await self.ledger.wait(response.content_fee)
166   File "/builds/lbry/lbry-sdk/.tox/datanetwork/lib/python3.7/site-packages/lbry/wallet/ledger.py", line 627, in wait
167     raise asyncio.TimeoutError('Timed out waiting for transaction.')
168 concurrent.futures._base.TimeoutError: Timed out waiting for transaction.
```
