### ISSUE TITLE
cli flags fail to prevent ipv6 bind attempts and failures on startup

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-sdk#2234]
## The Issue
Attempted to start lbrynet in docker.
`lbrynet start` fails.
It was suggested to specify the api flag.
including the --api and --streaming_server args in cli still fails.
"[Errno 99] error while attempting to bind on address ('::1', 5280, 0, 0): cannot assign requested address"},"

including the api: and streaming_server: args in a config specified with `--config ~/daemon_settings.yml` allows it to start.

Also the error printed is right most of the time, but it does not print 'e' and in this case is wrong to say 
"failed to bind TCP localhost:5279 for listening. Daemon is already running or this port is already in use by another application."

### Steps to reproduce
1. clone lbry-docker and cd into the lbrynet folder
2. modify Dockerfile-linux-multiarch-compiler to allow root access
2. `sudo docker build -t lbrynet:v0.38.0rc6root --build-arg VERSION=v0.38.0rc6 -f Dockerfile-linux-multiarch-compiler .`
3. `sudo docker run --rm -it -v wallet:/home/lbrynet lbrynet:v0.38.0rc6root /bin/bash`
4. try lbrynet start with various api flags and fail
4. `apt update` and `apt install nano` (or whatever)
5. create a daemon_settings.yml and add `api: 127.0.0.1:5279` and `streaming_server: 127.0.0.1:5280` to it.
6. `lbrynet start --config ~/daemon_settings.yml`

### Expected behaviour
 - lbrynet should start and not try to bind ipv6 at least if given cli flags
 - Error messages shouldn't be so specific as to be wrong

### Actual behaviour
lbrynet doesn't start because it tries to bind ipv6

Logs to follow.
## System Configuration

 

2019-06-13 21:40:41,831 INFO     lbrynet.extras.daemon.Daemon:409: Platform: {
  "processor": "x86_64",
  "python_version": "3.7.3",
  "platform": "Linux-4.18.0-21-generic-x86_64-with-Ubuntu-18.04-bionic",
  "os_release": "4.18.0-21-generic",
  "os_system": "Linux",
  "lbrynet_version": "0.38.0rc6",
  "build": "qa",
  "distro": {
    "id": "ubuntu",
    "version": "18.04",
    "version_parts": {
      "major": "18",
      "minor": "04",
      "build_number": ""
    },
    "like": "debian",
    "codename": "bionic"
  },
  "desktop": "Unknown"
}

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by jessopb** [comment]
```
~/LBRY/lbry-docker/lbrynet$ sudo docker run --rm -it -v wallet:/home/lbrynet lbrynet:v0.38.0rc6root /bin/bash
[sudo] password for jessop: 
root@014075d906cc:/# lbrynet start
2019-06-13 21:40:41,830 INFO     lbrynet.extras.daemon.Daemon:407: Starting LBRYNet Daemon
2019-06-13 21:40:41,831 INFO     lbrynet.extras.daemon.Daemon:409: Platform: {
  "processor": "x86_64",
  "python_version": "3.7.3",
  "platform": "Linux-4.18.0-21-generic-x86_64-with-Ubuntu-18.04-bionic",
  "os_release": "4.18.0-21-generic",
  "os_system": "Linux",
  "lbrynet_version": "0.38.0rc6",
  "build": "qa",
  "distro": {
    "id": "ubuntu",
    "version": "18.04",
    "version_parts": {
      "major": "18",
      "minor": "04",
      "build_number": ""
    },
    "like": "debian",
    "codename": "bionic"
  },
  "desktop": "Unknown"
}
2019-06-13 21:40:42,617 ERROR    lbrynet.extras.daemon.Daemon:427: lbrynet API failed to bind TCP localhost:5279 for listening. Daemon is already running or this port is already in use by another application.
2019-06-13 21:40:43,126 INFO     lbrynet.extras.daemon.Daemon:458: stopped api components
2019-06-13 21:40:43,127 INFO     lbrynet.extras.daemon.Daemon:464: stopped api server
2019-06-13 21:40:43,127 INFO     lbrynet.extras.daemon.Daemon:467: finished shutting down
```

**Comment by tzarebczan** [comment]
Lex said we should file an issue with docker to tell them to fix the misconfiguration. He'll probably close this.

**Comment by jessopb** [comment]
```
lbrynet start --verbose [VERBOSE [VERBOSE]] --api 127.0.0.1:5279 --streaming_server 127.0.0.1:5280
2019-06-14 20:03:18,931 INFO     lbrynet.extras.daemon.Daemon:407: Starting LBRYNet Daemon
2019-06-14 20:03:18,932 DEBUG    lbrynet.extras.daemon.Daemon:408: Settings: {
  "announce_head_and_sd_only": true,
  "api": "127.0.0.1:5279",
  "blob_download_timeout": 30.0,
  "blob_lru_cache_size": 32,
  "blockchain_name": "lbrycrd_main",
  "cache_time": 150,
  "comment_server": "https://comments.lbry.com/api",
  "components_to_skip": [],
  "concurrent_blob_announcers": 10,
  "concurrent_reflector_uploads": 10,
  "config": "/root/.local/share/lbry/lbrynet/daemon_settings.yml",
  "data_dir": "/root/.local/share/lbry/lbrynet",
  "download_dir": "/root/Downloads",
  "download_timeout": 30.0,
  "fixed_peer_delay": 2.0,
  "known_dht_nodes": [
    [
      "lbrynet1.lbry.com",
      4444
    ],
    [
      "lbrynet2.lbry.com",
      4444
    ],
    [
      "lbrynet3.lbry.com",
      4444
    ],
    [
      "lbrynet4.lbry.com",
      4444
    ]
  ],
  "lbryum_servers": [
    [
      "lbryumx1.lbry.com",
      50001
    ],
    [
      "lbryumx2.lbry.com",
      50001
    ],
    [
      "lbryumx4.lbry.com",
      50001
    ]
  ],
  "max_connections_per_download": 4,
  "max_key_fee": {
    "currency": "USD",
    "amount": 50.0
  },
  "network_interface": "0.0.0.0",
  "node_rpc_timeout": 5.0,
  "peer_connect_timeout": 3.0,
  "reflect_streams": true,
  "reflector_servers": [
    [
      "reflector.lbry.com",
      5566
    ]
  ],
  "s3_headers_depth": 960,
  "save_blobs": true,
  "save_files": true,
  "share_usage_data": true,
  "split_buckets_under_index": 1,
  "streaming_get": true,
  "streaming_server": "localhost:5280",
  "tcp_port": 3333,
  "udp_port": 4444,
  "use_upnp": true,
  "wallet_dir": "/root/.local/share/lbry/lbryum"
}
2019-06-14 20:03:18,933 INFO     lbrynet.extras.daemon.Daemon:409: Platform: {
  "processor": "x86_64",
  "python_version": "3.7.3",
  "platform": "Linux-4.18.0-21-generic-x86_64-with-Ubuntu-18.04-bionic",
  "os_release": "4.18.0-21-generic",
  "os_system": "Linux",
  "lbrynet_version": "0.38.0rc6",
  "build": "qa",
  "distro": {
    "id": "ubuntu",
    "version": "18.04",
    "version_parts": {
      "major": "18",
      "minor": "04",
      "build_number": ""
    },
    "like": "debian",
    "codename": "bionic"
  },
  "desktop": "Unknown"
}
2019-06-14 20:03:18,933 DEBUG    lbrynet.extras.daemon.analytics:153: Sending track event: {'userId': 'lbry', 'event': 'Server Startup', 'properties': {'lbry_id': '3NGVRofcdTTaYY29DVMgXmipRT7PKSCJ3dmbti6XmuKyQBznhnW8t9AJDMYesXP4gF', 'session_id': '3k3ESUMyWRihriJab2g3bHfLcbM6PJtVPjDmAZvwCvH2Fo4rJoRFMAyQR64WnZr3Tz'}, 'context': {'app': {'version': '0.38.0rc6', 'build': 'qa'}, 'os': {'name': 'Linux', 'version': '4.18.0-21-generic', 'desktop': 'Unknown', 'distro': {'id': 'ubuntu', 'version': '18.04', 'version_parts': {'major': '18', 'minor': '04', 'build_number': ''}, 'like': 'debian', 'codename': 'bionic'}}}, 'timestamp': '2019-06-14T20:03:18.933229Z'}
2019-06-14 20:03:19,573 INFO     lbrynet.extras.daemon.Daemon:417: lbrynet API listening on TCP 127.0.0.1:5279
2019-06-14 20:03:19,579 ERROR    lbrynet.extras.daemon.Daemon:427: lbrynet API failed to bind TCP 127.0.0.1:5279 for listening. Daemon is already running or this port is already in use by another application.
2019-06-14 20:03:19,581 DEBUG    lbrynet.extras.daemon.analytics:153: Sending track event: {'userId': 'lbry', 'event': 'Server Startup Error', 'properties': {'lbry_id': '3NGVRofcdTTaYY29DVMgXmipRT7PKSCJ3dmbti6XmuKyQBznhnW8t9AJDMYesXP4gF', 'session_id': '3k3ESUMyWRihriJab2g3bHfLcbM6PJtVPjDmAZvwCvH2Fo4rJoRFMAyQR64WnZr3Tz', 'message': "[Errno 99] error while attempting to bind on address ('::1', 5280, 0, 0): cannot assign requested address"}, 'context': {'app': {'version': '0.38.0rc6', 'build': 'qa'}, 'os': {'name': 'Linux', 'version': '4.18.0-21-generic', 'desktop': 'Unknown', 'distro': {'id': 'ubuntu', 'version': '18.04', 'version_parts': {'major': '18', 'minor': '04', 'build_number': ''}, 'like': 'debian', 'codename': 'bionic'}}}, 'timestamp': '2019-06-14T20:03:19.581491Z'}
2019-06-14 20:03:20,106 INFO     lbrynet.extras.daemon.Daemon:458: stopped api components
2019-06-14 20:03:20,109 INFO     lbrynet.extras.daemon.Daemon:464: stopped api server
2019-06-14 20:03:20,109 INFO     lbrynet.extras.daemon.Daemon:467: finished shutting down
```

**Comment by jessopb** [comment]
Jack suggested I try with daemon_settings.yml instead of cli.  Doing so worked. CLI is broken somewhere.

**Comment by jessopb** [comment]
Success with --config
```
root@d16cdd972fe3:~# lbrynet start --verbose [VERBOSE [VERBOSE]] --api 127.0.0.1:5279 --streaming_server 127.0.0.1:5280 --config ~/daemon_settings.yml
2019-06-14 20:04:38,554 INFO     lbrynet.extras.daemon.Daemon:407: Starting LBRYNet Daemon
2019-06-14 20:04:38,555 DEBUG    lbrynet.extras.daemon.Daemon:408: Settings: {
  "announce_head_and_sd_only": true,
  "api": "127.0.0.1:5279",
  "blob_download_timeout": 30.0,
  "blob_lru_cache_size": 32,
  "blockchain_name": "lbrycrd_main",
  "cache_time": 150,
  "comment_server": "https://comments.lbry.com/api",
  "components_to_skip": [],
  "concurrent_blob_announcers": 10,
  "concurrent_reflector_uploads": 10,
  "config": "/root/daemon_settings.yml",
  "data_dir": "/root/.local/share/lbry/lbrynet",
  "download_dir": "/root/Downloads",
  "download_timeout": 30.0,
  "fixed_peer_delay": 2.0,
  "known_dht_nodes": [
    [
      "lbrynet1.lbry.com",
      4444
    ],
    [
      "lbrynet2.lbry.com",
      4444
    ],
    [
      "lbrynet3.lbry.com",
      4444
    ],
    [
      "lbrynet4.lbry.com",
      4444
    ]
  ],
  "lbryum_servers": [
    [
      "lbryumx1.lbry.com",
      50001
    ],
    [
      "lbryumx2.lbry.com",
      50001
    ],
    [
      "lbryumx4.lbry.com",
      50001
    ]
  ],
  "max_connections_per_download": 4,
  "max_key_fee": {
    "currency": "USD",
    "amount": 50.0
  },
  "network_interface": "0.0.0.0",
  "node_rpc_timeout": 5.0,
  "peer_connect_timeout": 3.0,
  "reflect_streams": true,
  "reflector_servers": [
    [
      "reflector.lbry.com",
      5566
    ]
  ],
  "s3_headers_depth": 960,
  "save_blobs": true,
  "save_files": true,
  "share_usage_data": true,
  "split_buckets_under_index": 1,
  "streaming_get": true,
  "streaming_server": "127.0.0.1:5280",
  "tcp_port": 3333,
  "udp_port": 4444,
  "use_upnp": true,
  "wallet_dir": "/root/.local/share/lbry/lbryum"
}
2019-06-14 20:04:38,556 INFO     lbrynet.extras.daemon.Daemon:409: Platform: {
  "processor": "x86_64",
  "python_version": "3.7.3",
  "platform": "Linux-4.18.0-21-generic-x86_64-with-Ubuntu-18.04-bionic",
  "os_release": "4.18.0-21-generic",
  "os_system": "Linux",
  "lbrynet_version": "0.38.0rc6",
  "build": "qa",
  "distro": {
    "id": "ubuntu",
    "version": "18.04",
    "version_parts": {
      "major": "18",
      "minor": "04",
      "build_number": ""
    },
    "like": "debian",
    "codename": "bionic"
  },
  "desktop": "Unknown"
}
2019-06-14 20:04:38,556 DEBUG    lbrynet.extras.daemon.analytics:153: Sending track event: {'userId': 'lbry', 'event': 'Server Startup', 'properties': {'lbry_id': '3NGVRofcdTTaYY29DVMgXmipRT7PKSCJ3dmbti6XmuKyQBznhnW8t9AJDMYesXP4gF', 'session_id': '7EZ9Eghu3D7tzVq3QvdYiRAd52nNeMUwHihFTUUsMnaxsBjBPay8Kr4c66vULy7apg'}, 'context': {'app': {'version': '0.38.0rc6', 'build': 'qa'}, 'os': {'name': 'Linux', 'version': '4.18.0-21-generic', 'desktop': 'Unknown', 'distro': {'id': 'ubuntu', 'version': '18.04', 'version_parts': {'major': '18', 'minor': '04', 'build_number': ''}, 'like': 'debian', 'codename': 'bionic'}}}, 'timestamp': '2019-06-14T20:04:38.556271Z'}
2019-06-14 20:04:39,283 INFO     lbrynet.extras.daemon.Daemon:417: lbrynet API listening on TCP 127.0.0.1:5279
2019-06-14 20:04:39,285 INFO     lbrynet.extras.daemon.Daemon:423: lbrynet media server listening on TCP 127.0.0.1:5280
2019-06-14 20:04:39,493 DEBUG    lbrynet.extras.daemon.analytics:153: Sending track event: {'userId': 'lbry', 'event': 'Heartbeat', 'properties': {'lbry_id': '3NGVRofcdTTaYY29DVMgXmipRT7PKSCJ3dmbti6XmuKyQBznhnW8t9AJDMYesXP4gF', 'session_id': '7EZ9Eghu3D7tzVq3QvdYiRAd52nNeMUwHihFTUUsMnaxsBjBPay8Kr4c66vULy7apg'}, 'context': {'app': {'version': '0.38.0rc6', 'build': 'qa'}, 'os': {'name': 'Linux', 'version': '4.18.0-21-generic', 'desktop': 'Unknown', 'distro': {'id': 'ubuntu', 'version': '18.04', 'version_parts': {'major': '18', 'minor': '04', 'build_number': ''}, 'like': 'debian', 'codename': 'bionic'}}}, 'timestamp': '2019-06-14T20:04:39.493059Z'}
2019-06-14 20:04:39,510 INFO     lbrynet.extras.daemon.Components:566: detecting external ip
2019-06-14 20:04:39,515 INFO     lbrynet.extras.daemon.exchange_rate_manager:212: Starting exchange rate manager
2019-06-14 20:04:39,518 INFO     lbrynet.extras.daemon.Components:78: Loading databases
2019-06-14 20:04:39,519 WARNING  lbrynet.extras.daemon.Components:81: db_revision file not found. Creating it
2019-06-14 20:04:39,521 INFO     torba.client.basedatabase:208: connecting to database: /root/.local/share/lbry/lbrynet/lbrynet.sqlite
2019-06-14 20:04:39,755 INFO     torba.client.basenetwork:106: Successfully connected to SPV wallet server: lbryumx1.lbry.com:50001
```

**Comment by tzarebczan** [comment]
I did mention that the Jack/crew a couple weeks ago, never got around to filing an issue. It was strange, sometimes it would select the right ip and other times not. That's the bigger issue here, but I do believe we should have better support when IPV6 is enabled.

**Comment by EnigmaCurry** [comment]
I took @lyoshenka 's two_trys PR - https://github.com/lbryio/lbry/pull/2241 - and I made a mod to print the full stack trace and ran it from docker:

To build:

```
git clone https://github.com/EnigmaCurry/lbry-docker.git lbry-docker-enigmacurry
cd lbry-docker-enigmacurry/
git checkout lbrynet-refactor-2
cd lbrynet
sudo docker build -t lbrynet:two_trys_print --build-arg VERSION=two_trys_print \
     --build-arg REPO=https://github.com/EnigmaCurry/lbry.git -f Dockerfile-linux-multiarch-compiler .
```

Then run with a config file and see that it works:

```
sudo docker run --rm -it -v wallet:/home/lbrynet -v $(pwd)/stuff/daemon_settings_test.yml:/etc/lbry/daemon_settings.yml lbrynet:two_trys_print
```

But run with cli params for streaming_server and see it fail:

```
[ryan@t440s lbrynet]$ sudo docker run --rm -it -v wallet:/home/lbrynet -v $(pwd)/stuff/daemon_settings_test.yml:/etc/lbry/daemon_settings.yml lbrynet:two_trys_print lbrynet start --api 0.0.0.0:5279 --streaming_server 99.99.99.99:5280
2019-06-18 14:01:44,207 INFO     lbrynet.extras.daemon.Daemon:407: Starting LBRYNet Daemon
2019-06-18 14:01:44,208 INFO     lbrynet.extras.daemon.Daemon:409: Platform: {
  "processor": "x86_64",
  "python_version": "3.7.3",
  "platform": "Linux-4.19.49-1-MANJARO-x86_64-with-Ubuntu-18.04-bionic",
  "os_release": "4.19.49-1-MANJARO",
  "os_system": "Linux",
  "lbrynet_version": "0.38.0rc6",
  "torba_version": "0.5.5",
  "build": "qa",
  "distro": {
    "id": "ubuntu",
    "version": "18.04",
    "version_parts": {
      "major": "18",
      "minor": "04",
      "build_number": ""
    },
    "like": "debian",
    "codename": "bionic"
  },
  "desktop": "Unknown"
}
2019-06-18 14:01:44,224 INFO     lbrynet.extras.daemon.Daemon:417: RPC server listening on TCP 0.0.0.0:5279
[Errno 99] error while attempting to bind on address ('::1', 5280, 0, 0): cannot assign requested address
2019-06-18 14:01:44,227 ERROR    lbrynet.extras.daemon.Daemon:432: media server failed to bind TCP localhost:5280
Task exception was never retrieved
future: <Task finished coro=<HTTPSLogglyHandler._emit() done, defined at lbrynet/extras/daemon/loggly_handler.py:51> exception=ClientConnectorError(99, 'Cannot assign requested address')>
Traceback (most recent call last):
  File "aiohttp/connector.py", line 924, in _wrap_create_connection
  File "asyncio/base_events.py", line 959, in create_connection
  File "asyncio/base_events.py", line 946, in create_connection
  File "asyncio/selector_events.py", line 464, in sock_connect
  File "asyncio/selector_events.py", line 469, in _sock_connect
OSError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lbrynet/extras/daemon/loggly_handler.py", line 53, in _emit
  File "contextlib.py", line 170, in __aenter__
  File "lbrynet/utils.py", line 268, in aiohttp_request
  File "aiohttp/client.py", line 1005, in __aenter__
  File "aiohttp/client.py", line 476, in _request
  File "aiohttp/connector.py", line 522, in connect
  File "aiohttp/connector.py", line 854, in _create_connection
  File "aiohttp/connector.py", line 992, in _create_direct_connection
  File "aiohttp/connector.py", line 974, in _create_direct_connection
  File "aiohttp/connector.py", line 931, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host logs-01.loggly.com:443 ssl:<ssl.SSLContext object at 0x7f00a01c7e80> [Cannot assign requested address]
2019-06-18 14:01:44,236 INFO     lbrynet.extras.daemon.Daemon:464: stopped api components
2019-06-18 14:01:44,236 INFO     lbrynet.extras.daemon.Daemon:470: stopped api server
2019-06-18 14:01:44,236 INFO     lbrynet.extras.daemon.Daemon:473: finished shutting down
```

I deliberatly chose to bind streaming_server to `99.99.99.99` - but lbrynet is still trying to bind to `localhost` which in this case resolves to the ipv6 address `::1` (which does not work in docker)

**Comment by tzarebczan** [comment]
The issue above was that it's supposed to be --streaming-server and not --streaming_server on the CLI. 

Going to close this issue and open a new one for IPV6 related problems.
