### ISSUE TITLE
High memory usage and slow sync with large wallets / address history / utxos

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2266]
We've seen this on some YouTube sync wallets and on the spee.ch wallet. The spee.ch wallet takes like 2 hours to sync, and seems very inefficient/ slow. When loaded, it uses about 2GB of memory.  Other YouTube wallets which had large fund commands run do not want to sync at all (@shyba aware of this). 

This should be a priority if we also think it affects incoming tips / claiming of tips.

**Comment by tzarebczan** [comment]
@shyba I'm even seeing this high mem usage on much smaller wallets - ```2019-07-01 09:35:10,798 INFO     lbry.wallet.ledger:106: Loaded account bTKFnGf3fzGTVP3yPXPtkbT7aepFA8BkrU with 1.007184 LBC, 62 receiving addresses (gap: 20), 14 change addresses (gap: 6), 1 channels, 1 certificates and 2 claims. ```

I think it has to do with the fund command and us splitting up utxos.

**Comment by tzarebczan** [comment]
This happens: ```
9c7216d372d5b19ce7bd62de1847f09d2c592aa5
2019-07-01 09:51:26,968 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bEq6vTnwzZpBGRSaDvPDr8xHqo18Dv6vjD, height=585667, is_verified=True, tx.id=2e8ddb1ee272e7d09948bba7a475434828eab54125518d9a8c33d9d7d47f2454
2019-07-01 09:51:29,133 INFO     torba.client.baseledger:125: (lbc_mainnet) on_address: ['bRxatxyYLp2oE9CHVMB4q8LK2XmYUEFNxv', 'baKHMXmvuAuFM4B5Vt5xazAXzTNZqszFnX']
Task exception was never retrieved
future: <Task finished coro=<BaseLedger.update_history() done, defined at c:\users\thoma\documents\lbry\torba\torba\client\baseledger.py:386> exception=MemoryError()>
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseledger.py", line 425, in update_history
    txo.id: txo for txo in await self.db.get_txos(txoid__in=check_db_for_txos)
  File "c:\users\thoma\documents\lbry\lbry\lbry\wallet\database.py", line 58, in get_txos
    txos = await super().get_txos(**constraints)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 472, in get_txos
    **constraints
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 461, in select_txos
    " JOIN tx USING (txid)".format(cols), **constraints
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 50, in __fetchall
    return conn.execute(*args, **kwargs).fetchall()
MemoryError
2019-07-01 09:52:07,064 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bFEZcBsYHjtoCHBSszKqjo8NQo1oWD1aq6, height=585674, is_verified=True, tx.id=f9f80b81d7bdb542d35610855cf62241033403def5434cc6b7ffab40434847ef
2019-07-01 09:52:07,064 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bResjjkh8wx8U6r7mWsMVcoRBPKB5L1bRg, height=585674, is_verified=True, tx.id=d54e52a82c18c9855d84f2667477efc9bc90518182f08522ffe72c1969d28f49
2019-07-01 09:52:07,067 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bEq6vTnwzZpBGRSaDvPDr8xHqo18Dv6vjD, height=585667, is_verified=True, tx.id=d001bc2abb4c4b3d54ac76c29380fee3dc55e39a310c4a9e191e1504699c1e2f
2019-07-01 09:52:07,068 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bbDaZPU8eQszJWq2R1iTVUQLUPbxm4rMqW, height=585674, is_verified=True, tx.id=55557d8260af6a21fb83099e32b9258728305807d977f6cbb4ab595115e39b27
2019-07-01 09:52:07,071 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bLr7p4PD7i8r6HPhKLANQYEM5dvVhUyDQw, height=585674, is_verified=True, tx.id=42a925fbe2470a054b08fcf654d03765691bb042a4761574051ff0d1462b193d
Task exception was never retrieved
future: <Task finished coro=<BaseLedger.receive_header() done, defined at c:\users\thoma\documents\lbry\torba\torba\client\baseledger.py:348> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseledger.py", line 352, in receive_header
    height=header['height'], headers=header['hex'], subscription_update=True
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseledger.py", line 296, in update_headers
    added = await self.headers.connect(height, unhexlify(headers))
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseheader.py", line 106, in connect
    await loop.run_in_executor(None, self.validate_chunk, height, chunk)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 752, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 160, in submit
    self._adjust_thread_count()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 181, in _adjust_thread_count
    t.start()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by tzarebczan** [comment]
This is pretty much happening with every yt sync wallet I tried. We've transferred a bunch of wallets to users, so they pretty much won't be usable with this update. Marking as a blocker.

**Comment by eukreign** [comment]
fixed in #2304
