### ISSUE TITLE
wallet server: UNIQUE constraint failed: trend.claim_hash, trend.height

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2276]
Got this when trying to sync up spv1 outside of docker. re-syncing now to see if it goes away. 
```INFO:torba.server.block_processor.LBRYBlockProcessor:our height: 586,669 daemon: 591,523 UTXOs 235MB hist 182MB
INFO:torba.server.block_processor.LBRYBlockProcessor:our height: 587,160 daemon: 591,525 UTXOs 242MB hist 187MB
ERROR:torba.server.block_processor.LBRYBlockProcessor:Error while advancing transaction in new block.
Traceback (most recent call last):
  File "/home/lbry/lbry-sdk/lbry/lbry/wallet/server/block_processor.py", line 75, in advance_blocks
    self.timer.run(super().advance_blocks, blocks)
  File "/home/lbry/lbry-sdk/lbry/lbry/wallet/server/block_processor.py", line 30, in run
    return func(*args, **kwargs)
  File "/home/lbry/lbry-sdk/torba/torba/server/block_processor.py", line 381, in advance_blocks
    height, block.transactions, self.coin.electrum_header(block.header, height)
  File "/home/lbry/lbry-sdk/lbry/lbry/wallet/server/block_processor.py", line 85, in advance_txs
    timer.run(self.sql.advance_txs, height, txs, header, self.daemon.cached_height(), forward_timer=True)
  File "/home/lbry/lbry-sdk/lbry/lbry/wallet/server/block_processor.py", line 28, in run
    return func(*args, **kwargs, timer=t)
  File "/home/lbry/lbry-sdk/lbry/lbry/wallet/server/db.py", line 746, in advance_txs
    r(calculate_trending, self.db, height, self.main.first_sync, daemon_height)
  File "/home/lbry/lbry-sdk/lbry/lbry/wallet/server/block_processor.py", line 30, in run
    return func(*args, **kwargs)
  File "/home/lbry/lbry-sdk/lbry/lbry/wallet/server/trending.py", line 70, in calculate_trending
    """)
sqlite3.IntegrityError: UNIQUE constraint failed: trend.claim_hash, trend.height```

**Comment by tzarebczan** [comment]
This was fixed
