### ISSUE TITLE
too many SQL variables when syncing some wallets

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2281]
Will try to get the xpub key for this one: 

```
2019-06-30 23:23:45,788 INFO     lbry.stream.stream_manager:163: Started stream manager with 0 files
2019-06-30 23:23:45,788 INFO     lbry.extras.daemon.Components:429: Done setting up file manager
2019-06-30 23:23:52,382 ERROR    lbry.extras.daemon.Daemon:585: error handling api request
Traceback (most recent call last):
  File "lbry\extras\daemon\Daemon.py", line 579, in _process_rpc_call
  File "lbry\extras\daemon\Daemon.py", line 137, in maybe_paginate
  File "lbry\wallet\manager.py", line 213, in get_history
  File "torba\client\basedatabase.py", line 427, in get_transactions
  File "lbry\wallet\database.py", line 58, in get_txos
  File "torba\client\basedatabase.py", line 472, in get_txos
  File "torba\client\basedatabase.py", line 461, in select_txos
  File "concurrent\futures\thread.py", line 57, in run
  File "torba\client\basedatabase.py", line 50, in __fetchall
sqlite3.OperationalError: too many SQL variables
2019-06-30 23:24:30,586 INFO     lbry.extras.daemon.Daemon:825: Get version info: {"processor": "Intel64 Family 6 Model 23 Stepping 10, GenuineIntel", "python_version": "3.7.3", "platform": "Windows-10-10.0.17763", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.38.0", "torba_version": "0.5.7", "build": "release"}
2019-06-30 23:24:38,473 ERROR    lbry.extras.daemon.Daemon:585: error handling api request
Traceback (most recent call last):
  File "lbry\extras\daemon\Daemon.py", line 579, in _process_rpc_call
  File "lbry\extras\daemon\Daemon.py", line 137, in maybe_paginate
  File "lbry\wallet\manager.py", line 213, in get_history
  File "torba\client\basedatabase.py", line 427, in get_transactions
  File "lbry\wallet\database.py", line 58, in get_txos
  File "torba\client\basedatabase.py", line 472, in get_txos
  File "torba\client\basedatabase.py", line 461, in select_txos
  File "concurrent\futures\thread.py", line 57, in run
  File "torba\client\basedatabase.py", line 50, in __fetchall
sqlite3.OperationalError: too many SQL variables

```

**Comment by tzarebczan** [comment]
2 users on .038 are now running into this. This was not an issue in 0.37 I believe.

**Comment by tzarebczan** [comment]
Also just ran into this when receiving a tx: ```2019-07-01 14:54:57,491 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transaction: address=bQ5CD8cpLzTXwbP5HT1DpH63RSX4EXzpZC, height=593361, is_verified=True, tx.id=1cdc5af6e6212ec736c0ff03aa32241876abc21ac2c7ab0d3f8b8a09a378c88a
2019-07-01 14:56:09,496 ERROR    lbry.extras.daemon.Daemon:585: error handling api request
Traceback (most recent call last):
  File "lbry\extras\daemon\Daemon.py", line 579, in _process_rpc_call
  File "lbry\extras\daemon\Daemon.py", line 137, in maybe_paginate
  File "lbry\wallet\manager.py", line 213, in get_history
  File "torba\client\basedatabase.py", line 427, in get_transactions
  File "lbry\wallet\database.py", line 58, in get_txos
  File "torba\client\basedatabase.py", line 472, in get_txos
  File "torba\client\basedatabase.py", line 461, in select_txos
  File "concurrent\futures\thread.py", line 57, in run
  File "torba\client\basedatabase.py", line 50, in __fetchall
sqlite3.OperationalError: too many SQL variables```

**Comment by tzarebczan** [comment]
fixed in https://github.com/lbryio/lbry-sdk/pull/2294
