### ISSUE TITLE
Startup error in get_linux_directories

### ISSUE THREAD

**Issue by shauser** [lbryio/lbry-sdk#2291]
When starting LBRY-0.33.2 the first time on Ubuntu 19.04, I get the following message during startup:

> The daemon may have encountered an unexpected error, or another daemon instance is already running.

The log file does not exist, but the console has the following output:

    Starting SDK
    Sandbox listening on port 5278.
    Daemon: [17050] Failed to execute script cli
    
    Daemon: Traceback (most recent call last):
      File "lbrynet/extras/cli.py", line 322, in <module>
      File "lbrynet/extras/cli.py", line 229, in main
      File "lbrynet/conf.py", line 400, in create_from_arguments
      File "lbrynet/conf.py", line 570, in __init__
      File "lbrynet/conf.py", line 582, in set_default_paths
      File "lbrynet/conf.py", line 621, in get_linux_directories
    AttributeError: 'NoneType' object has no attribute 'group'

I tried manually creating the `~/.config/LBRY/user-dirs.dirs` according to the code that tries to read it, but the exception is still the same.

**Comment by tzarebczan** [comment]
Sorry to hear and thanks for opening this issue! I've run this successfully on 19 so it's probably a local issue with permissions or some strange directory config . Can you give us any more info?

**Comment by shauser** [comment]
The problem was that `xdg.read()` returns an empty string if the file does not exist, which causes `re.search` to return `None`.

**Comment by eukreign** [comment]
@shauser if the file doesn't exist, it would fail with a different error

can you tell me how to reproduce this issue?

**Comment by shauser** [comment]
Sorry, I was busy with other stuff in the last few months. I just checked back with this issue...

The error actually occurs when the file ~/.config/user-dirs.dirs exists, but is empty. I don't know why this happened though, but after removing the file or recreating it with `xdg-user-dirs-update` lbrynet works flawlessly.

**Comment by tzarebczan** [comment]
Thanks for the feedback! Can we show you some [appreciation](https://LBRY.com/faq/appreciation) for the info ? 

@eukreign should we try to handle this scenario or mark this closed as a environment specific issue. I haven't seen it happen elsewhere.
