### ISSUE TITLE
on shutdown, TCPSite gets unregistered twice and the second time throws an exception

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2301]
From @lyoshenka  - said he'd work on it. 

I also see this on Jack's branch torba reconnect, not sure if related:
```
2019-07-08 10:59:56,125 INFO     lbry.blob_exchange.server:124: Blob server listening on TCP 0.0.0.0:3333
Unhandled error in exception handler
context: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\locks.py:293> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x06DFAD90>()]> cb=[_wait.<locals>._on_completion() at C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\tasks.py:440]>}
Traceback (most recent call last):
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1643, in call_exception_handler
    self._exception_handler(self, context)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basenetwork.py", line 58, in protocol_exception_handler
    exception = context['exception']
KeyError: 'exception'
```

**Comment by lyoshenka** [comment]
fixed in #2297
