### ISSUE TITLE
Transaction rejected as dust on Publish

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2334]
Have a user who is having trouble making transactions most of the time because it either fails due to a dust warning or high fee if he messes around with bids.  The rules for selecting utxos must have a bug in some edge case. We had filed this on lbrycrd previously, but they said to make sure the client doesn't 0 value tx (https://github.com/lbryio/lbrycrd/issues/186#issuecomment-474944579). 

```2019-07-21 14:46:25,293 INFO     lbry.extras.daemon.Daemon:2330: publishing: name: thats-pretty-great params: {'title': 'Testing', 'description': '', 'bid': '0.00000010', 'languages': ['en'], 'tags': [], 'thumbnail_url': 'redacted', 'license': 'None', 'channel_id': 'redacted', 'file_path': 'B:\\redacted\\Downloads\\uploads\\test.mp4'}
2019-07-21 14:46:31,056 WARNING  torba.client.basenetwork:33: Wallet server returned an error. Code: 1 Message: the transaction was rejected by network rules.

dust (code 65)
[010000000140506c0788199a132c21555f8fb1fddd0c3b2616fed15d4f47e1e45236348f54010000006b483045022100c5591a496eb21bb40d409588f033ba38dcc28d3c1bc771824875f42a4666d4000220605f6ee84006753220ba1b0f8a2f509c96d2c8ddaf9bc9c7231b7a038a056c670121028486943fede99ddab35ec7e508a7482694792786329ec28321a4f530bb59ea96ffffffff020a00000000000000fd9401b51274686174732d7072657474792d67726561744d62010163221b027f3f8772cb6cbd68de5f5df0bd349bea326d86c1adfa57fd4b002f15df02fae287834f17253c5a7e573861bc376f45d469858c39e5e5281aa15d5352a2165e12b3f1eb87dbef636990a4728ba8b46e240acb010ab7010a309236fd71ecb5b715dacdaac40d06c6191850282523c59e680ac6e8b6645f2970efade7416a3362772bb45dab32c1e21912416d616b652d6d652d707265676e616e742d6f722d696d2d74656c6c696e672d6d6f6d2d796f752d6675636b65642d6865722d626573742d667269656e642e6d703418f9b6b02c2209766964656f2f6d703432308b6b1d94bb77c839a659ede99aac71b5740805bfd66ba4394e86391c184f6d58e99a244d3c3fc516026784d57880b9821a044e6f6e655a0908800a10d00518ca08420754657374696e6752302a2e68747470733a2f2f737065652e63682f632f736a4142396847355972715956584c7435644a644a4c376b2e676966620208016d7576a9147fcb0783224560b540684c48b187b078eaeb8b7888ac7abf8329000000001976a914dad487e759d31e6adb1e86746b5cd747598e54a588ac00000000]
2019-07-21 14:46:31,213 ERROR    lbry.extras.daemon.Daemon:586: error handling api request
Traceback (most recent call last):
  File "lbry\extras\daemon\Daemon.py", line 580, in _process_rpc_call
  File "lbry\extras\daemon\Daemon.py", line 2339, in jsonrpc_publish
  File "lbry\extras\daemon\Daemon.py", line 2479, in jsonrpc_stream_create
  File "lbry\extras\daemon\Daemon.py", line 3502, in broadcast_or_release
  File "torba\client\basenetwork.py", line 34, in send_request
  File "torba\client\basenetwork.py", line 31, in send_request
  File "asyncio\tasks.py", line 442, in wait_for
  File "torba\rpc\session.py", line 481, in send_request
torba.rpc.jsonrpc.RPCError: (1, 'the transaction was rejected by network rules.\n\ndust (code 65)\n[010000000140506c0788199a132c21555f8fb1fddd0c3b2616fed15d4f47e1e45236348f54010000006b483045022100c5591a496eb21bb40d409588f033ba38dcc28d3c1bc771824875f42a4666d4000220605f6ee84006753220ba1b0f8a2f509c96d2c8ddaf9bc9c7231b7a038a056c670121028486943fede99ddab35ec7e508a7482694792786329ec28321a4f530bb59ea96ffffffff020a00000000000000fd9401b51274686174732d7072657474792d67726561744d62010163221b027f3f8772cb6cbd68de5f5df0bd349bea326d86c1adfa57fd4b002f15df02fae287834f17253c5a7e573861bc376f45d469858c39e5e5281aa15d5352a2165e12b3f1eb87dbef636990a4728ba8b46e240acb010ab7010a309236fd71ecb5b715dacdaac40d06c6191850282523c59e680ac6e8b6645f2970efade7416a3362772bb45dab32c1e21912416d616b652d6d652d707265676e616e742d6f722d696d2d74656c6c696e672d6d6f6d2d796f752d6675636b65642d6865722d626573742d667269656e642e6d703418f9b6b02c2209766964656f2f6d703432308b6b1d94bb77c839a659ede99aac71b5740805bfd66ba4394e86391c184f6d58e99a244d3c3fc516026784d57880b9821a044e6f6e655a0908800a10d00518ca08420754657374696e6752302a2e68747470733a2f2f737065652e63682f632f736a4142396847355972715956584c7435644a644a4c376b2e676966620208016d7576a9147fcb0783224560b540684c48b187b078eaeb8b7888ac7abf8329000000001976a914dad487e759d31e6adb1e86746b5cd747598e54a588ac00000000]')
2019-07-21 14:46:31,932 INFO     lbry.stream.reflector.client:97: Sent reflector descriptor 8b6b1d94
2019-07-21 14:46:31,932 INFO     lbry.stream.reflector.client:102: Reflector needs 45 blobs for 8b6b1d94
2019-07-21 14:46:35,380 INFO     lbry.stream.reflector.client:119: Sent reflector blob 5fbe6f50
```

The high fee error was due to a lbrycrd param change.

**Comment by tzarebczan** [comment]
Multiple users have been running into this recently - I think something is up with our fee calculation. For dust ones, we need to add more LBC into the tx so it's  not dust.

**Comment by lyoshenka** [comment]
closed by #2359

**Comment by tzarebczan** [comment]
This is not the same problem - this error occurred during stream creation: 
```Traceback (most recent call last):
  File "lbry\extras\daemon\Daemon.py", line 580, in _process_rpc_call
  File "lbry\extras\daemon\Daemon.py", line 2339, in jsonrpc_publish
  File "lbry\extras\daemon\Daemon.py", line 2479, in jsonrpc_stream_create
  File "lbry\extras\daemon\Daemon.py", line 3502, in broadcast_or_release
  File "torba\client\basenetwork.py", line 34, in send_request
  File "torba\client\basenetwork.py", line 31, in send_request
  File "asyncio\tasks.py", line 442, in wait_for
  File "torba\rpc\session.py", line 481, in send_request```

**Comment by tzarebczan** [comment]
Even more concerning is that the it was still reflected - I thought we fixed that bug on tx error. Will try to repro.

**Comment by tzarebczan** [comment]
This is probably due to new lbrycrd settings and not related to the SDK. Will track down.

**Comment by tzarebczan** [comment]
This was an issue on lbrycrd - we set the minrelayrate to 0.0000001, closing.
