### ISSUE TITLE
Slow startup due to headers, error + sync from spv, is_running false

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2335]
```
2019-07-23 09:58:18,279 INFO     lbry.extras.daemon.Daemon:416: RPC server listening on TCP 127.0.0.1:5279
2019-07-23 09:58:18,282 INFO     lbry.extras.daemon.Daemon:426: media server listening on TCP 127.0.0.1:5280
2019-07-23 09:58:18,628 INFO     lbry.extras.daemon.Components:547: detecting external ip
2019-07-23 09:58:18,632 INFO     lbry.extras.daemon.exchange_rate_manager:212: Starting exchange rate manager
2019-07-23 09:58:18,632 INFO     lbry.extras.daemon.Components:66: Loading databases
2019-07-23 09:58:18,634 INFO     torba.client.basedatabase:226: connecting to database: c:\lbry-ah-4\lbrynet.sqlite
2019-07-23 09:58:18,849 INFO     lbry.extras.daemon.Components:188: remote height: 604969, local height: -1
2019-07-23 09:58:44,274 WARNING  lbry.extras.daemon.Components:158: Error connecting downloaded headers from at 597706.
2019-07-23 09:58:44,283 INFO     lbry.extras.daemon.Components:319: start the dht
2019-07-23 09:58:44,293 INFO     lbry.extras.daemon.Components:344: Started the dht
2019-07-23 09:58:44,295 INFO     lbry.extras.daemon.Components:241: Starting torba wallet
2019-07-23 09:58:44,455 INFO     torba.client.basedatabase:226: connecting to database: C:\Users\SoloDolo\AppData\Roaming\lbryum\lbc_mainnet\blockchain.db
2019-07-23 09:58:44,459 INFO     lbry.dht.node:118: DHT node listening on UDP 0.0.0.0:4446
2019-07-23 09:58:45,124 INFO     torba.client.basenetwork:101: Successfully connected to SPV wallet server: spv1.lbry.com:50001
2019-07-23 09:58:45,124 INFO     torba.client.baseledger:265: Subscribing and updating accounts.
```

**Comment by tzarebczan** [comment]
also, is_running is false if the headers url is not accessible (set 127.0.01 to headers domain in hosts): 

You see this on startup: 

```
2019-07-23 11:02:15,867 WARNING  lbry.extras.daemon.Components:173: Header download error, unexpected response code: 404
2019-07-23 11:02:15,868 ERROR    lbry.extras.daemon.Component:62: Error setting up blockchain_headers
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Component.py", line 55, in _setup
    result = await self.start()
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Components.py", line 201, in start
    if await self.should_download_headers_from_s3():
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Components.py", line 186, in should_download_headers_from_s3
    remote_height = await self.get_downloadable_header_height()
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Components.py", line 174, in get_downloadable_header_height
    return response.content_length // HEADER_SIZE
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

```

```
},
  "hash_announcer": {
    "announce_queue_size": 0
  },
  "installation_id": "77GudJ23BG87WgHL8ZMjzdAJ66U9f9QQHZsnsi7tBGZmhGQkwzY76cZtPbepfiMqpd",
  "is_running": false,```

**Comment by tzarebczan** [comment]
This is fixed
