### ISSUE TITLE
publish (edit with new file) fails if already reflecting existing one

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2368]
Related to https://github.com/lbryio/lbry-sdk/issues/1937, but this causes errors while editing (with new file)+ still reflecting old blobs. The edit process tries to delete the old file data to replace with the new one. 

2 users ran into this one recently. 

```
2019-08-01 18:18:06,916 INFO     lbry.stream.reflector.client:119: Sent reflector blob e5828b7e
2019-08-01 18:18:29,221 INFO     lbry.stream.reflector.client:119: Sent reflector blob 867d1a2c
2019-08-01 18:18:51,545 INFO     lbry.stream.reflector.client:119: Sent reflector blob 6e365367
2019-08-01 18:18:58,400 INFO     lbry.extras.daemon.Daemon:2330: publishing: name: xxxx params: {'title': 'xxxx', 'description': 'xxxxxx', 'bid': '0.10000000', 'languages': ['en'], 'tags': ['xxxxx'], 'thumbnail_url': 'https://spee.ch/8/xxxxxxxxx', 'license': 'All rights reserved   Published With Permission', 'release_time': 1564696220, 'channel_id': 'xxxxxxxxxxxx', 'fee_currency': 'LBC', 'fee_amount': '1.00000000', 'file_path': 'C:\\Users\\David T\\Desktop\\GMCZ0549_VID_1280x720x1500kbs_HCVC549.mp4'}
2019-08-01 18:19:22,348 ERROR    lbry.extras.daemon.Daemon:586: error handling api request
Traceback (most recent call last):
  File "lbry\extras\daemon\Daemon.py", line 580, in _process_rpc_call
  File "lbry\extras\daemon\Daemon.py", line 2342, in jsonrpc_publish
  File "lbry\extras\daemon\Daemon.py", line 2659, in jsonrpc_stream_update
  File "lbry\stream\stream_manager.py", line 232, in delete_stream
AttributeError: 'NoneType' object has no attribute 'stop_tasks'
2019-08-01 18:19:37,886 INFO     lbry.stream.reflector.client:119: Sent reflector blob f5b10e7b
2019-08-01 18:20:00,717 INFO     lbry.stream.reflector.client:119: Sent reflector blob d5ffe375
```

**Comment by tzarebczan** [comment]
A few more users ran into this recently. We do have an app bug where we re-send the file on edit, but it could also happen where a user is re-selecting it. 

This may also happen if they are seeding the file and it tries to remove it.  https://github.com/lbryio/lbry-sdk/issues/1937

**Comment by mirgee** [comment]
This seems to be happen only on Windows.

**Comment by tzarebczan** [comment]
Seeing a couple of these per day. Happens when a user tries to edit a claim while it's seeding or reflecting.
