### ISSUE TITLE
Can't load / timeouts while syncing transactions with large wallets

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2374]
Was trying to sync a larger creator's wallet and ran into issues with sync either just stopping or timing out like below. This wallet had over 7K claims, and then was run through an update process on YouTube sync (fund command to split up utxos, all claims updated). Need to understand which part is causing the issues.

Since then, I've restarted the SDK multiple times to resume the sync process, will let you know if it ends up completing. 

```
2019-08-04 09:57:24,800 INFO     torba.client.baseledger:119: (lbc_mainnet) on_transaction: address=bDHSUL6EniGEbM6HFPVXaJNnfMExPSYnPm, height=580374, is_verified=True, tx.id=d66074daad6463451ce7dcbc30b2a525b8bed5a107581725cf8cd8e311b23a31
2019-08-04 09:57:24,808 INFO     torba.client.baseledger:119: (lbc_mainnet) on_transaction: address=bDHSUL6EniGEbM6HFPVXaJNnfMExPSYnPm, height=580374, is_verified=True, tx.id=66efdd224e80a44d656f9b869164f0d13546ef3f2577f6dbd2c36afaf4f40c92
2019-08-04 09:57:24,822 INFO     torba.client.baseledger:119: (lbc_mainnet) on_transaction: address=bDHSUL6EniGEbM6HFPVXaJNnfMExPSYnPm, height=580374, is_verified=True, tx.id=8477f7f11413df16a2b7406fcf1be7cdb45c2e776e7249f3e95364f23d4a329d
2019-08-04 09:57:24,833 INFO     torba.client.baseledger:119: (lbc_mainnet) on_transaction: address=bDHSUL6EniGEbM6HFPVXaJNnfMExPSYnPm, height=580374, is_verified=True, tx.id=9b5cfc9cef80d7c65612e3f3131af0b3f784bf4565843518b2fa79e8d6e6d2b1
2019-08-04 09:57:24,856 INFO     torba.client.baseledger:119: (lbc_mainnet) on_transaction: address=bDHSUL6EniGEbM6HFPVXaJNnfMExPSYnPm, height=580374, is_verified=True, tx.id=bae20e80be060c1a948c1c726f7d124fa25b726aad95e75617a12ab530d3bfab
Task exception was never retrieved
future: <Task finished coro=<BaseLedger.update_history() done, defined at /home/tom/lbry/torba/torba/client/baseledger.py:387> exception=TimeoutError()>
Traceback (most recent call last):
  File "/home/tom/lbry/torba/torba/client/baseledger.py", line 410, in update_history
    tx = await task
  File "/home/tom/lbry/torba/torba/client/baseledger.py", line 472, in cache_transaction
    await self.maybe_verify_transaction(tx, remote_height)
  File "/home/tom/lbry/torba/torba/client/baseledger.py", line 490, in maybe_verify_transaction
    merkle = await self.network.get_merkle(tx.id, remote_height)
  File "/home/tom/lbry/torba/torba/client/basenetwork.py", line 31, in send_request
    return await asyncio.wait_for(super().send_request(method, args), timeout=self.timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
2019-08-04 09:57:51,909 INFO     torba.client.baseledger:134: lbc_mainnet: added BlockHeightEvent(height=611452, change=1) header blocks, final height 611452
2019-08-04 09:58:10,072 INFO     torba.client.baseledger:134: lbc_mainnet: added BlockHeightEvent(height=611453, change=1) header blocks, final height 611453
2019-08-04 10:04:16,513 INFO     torba.client.baseledger:134: lbc_mainnet: added BlockHeightEvent(height=611454, change=1) header blocks, final height 611454

```

**Comment by tzarebczan** [comment]
Finally loaded: ```2019-08-05 12:25:11,093 INFO     lbry.wallet.ledger:106: Loaded account bW1v26fmUHpsp4MdaQkYoQWgq4u8uwCdqF with 29.28654812 LBC, 1123 receiving addresses (gap: 20), 10142 change addresses (gap: 6), 1 channels, 1 certificates and 10931 claims. 
```

**Comment by tzarebczan** [comment]
This also happens on poorer connections and the SDK loads incomplete wallet data - probably more related to https://github.com/lbryio/lbry-sdk/issues/1722

**Comment by lyoshenka** [comment]
steps:
- [ ] get a large wallet that's not syncing
- [ ] figure out exactly why its not syncing. our theory is that it needs to get a ton of transactions from wallet server
- [ ] check if splitting the address history into batches of 1000 will solve the issue
- [ ] if not, check if bloom filters will solve the issue

**Comment by lyoshenka** [comment]
@eukreign are you still working on this? should i close it?

**Comment by lyoshenka** [comment]
@jackrobison says some of the work he just did may help with this

**Comment by eukreign** [comment]
@lyoshenka yeah, @jackrobison did one of the options (batch subscribing), but it's still not going to be as fast or as reliable as using Golomb-Rice filters.

**Comment by lyoshenka** [comment]
i'm gonna close it. Plz reopen if this is still a problem. We may fix it ourselves eventually. A reopen would let us know its more urgent.
