### ISSUE TITLE
codec can't encode character '\u2652' in position 83: character maps to <undefined>

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2437]
```
2019-08-31 10:02:31,489 INFO     lbry.dht.blob_announcer:43: 8 blobs to announce
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1028, in emit
  File "c:\python37\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2652' in position 83: character maps to <undefined>
Call stack:
  File "lbry\extras\cli.py", line 317, in <module>
  File "lbry\extras\cli.py", line 294, in main
  File "lbry\extras\cli.py", line 269, in run_daemon
  File "asyncio\base_events.py", line 534, in run_forever
  File "asyncio\base_events.py", line 1771, in _run_once
  File "asyncio\events.py", line 88, in _run
  File "site-packages\aiohttp\web_app.py", line 458, in _handle
  File "lbry\extras\daemon\Daemon.py", line 475, in handle_old_jsonrpc
  File "lbry\extras\daemon\Daemon.py", line 580, in _process_rpc_call
  File "lbry\extras\daemon\Daemon.py", line 2352, in jsonrpc_publish
  File "logging\__init__.py", line 1378, in info
  File "logging\__init__.py", line 1514, in _log
  File "logging\__init__.py", line 1524, in handle
  File "logging\__init__.py", line 1586, in callHandlers
  File "logging\__init__.py", line 894, in handle
  File "logging\handlers.py", line 71, in emit
  File "logging\__init__.py", line 1127, in emit
  File "logging\__init__.py", line 1033, in emit
Message: 'publishing: name: %s params: %s'
Arguments: ('♒', {'title': '♒♒♒♒♒♒♒♒♒♒♒♒', 'description': '♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒ ♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒ ♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒', 'bid': '1.00000000', 'languages': ['en'], 'tags': ['groovy'], 'thumbnail_url': 'https://spee.ch/a/Z5tRSQVAKUw7qJlCOuBRp7KX.gif', 'license': 'Public Domain', 'release_time': 1563411899, 'channel_id': 'c474d46ef096084d3eaa58fef6a50b5cfbf8f096'})
2019-08-31 10:02:40,399 INFO     lbry.extras.daemon.Daemon:2352: publishing: name: ♒ params: {'title': '♒♒♒♒♒♒♒♒♒♒♒♒', 'description': '♒♒♒♒♒♒ ♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒ ♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒♒', 'bid': '1.00000000', 'languages': ['en'], 'tags': ['groovy'], 'thumbnail_url': 'https://spee.ch/a/Z5tRSQVAKUw7qJlCOuBRp7KX.gif', 'license': 'Public Domain', 'release_time': 1563411899, 'channel_id': 'c474d46ef096084d3eaa58fef6a50b5cfbf8f096'}```

**Comment by tzarebczan** [comment]
This is also logged each time a file is downloaded with such characters anywhere.

**Comment by mirgee** [comment]
@tzarebczan It seems to be possible to publish claims with those characters in both names and filenames via JSON and cli.

**Comment by eukreign** [comment]
@mirgee are you planning to work on this?

**Comment by mirgee** [comment]
@eukreign I did, but haven't managed to reproduce it.

**Comment by cbaumler** [comment]
@tzarebczan I'm looking to make my first contribution as part of Hacktoberfest. Is it okay if I work on this bug? I tried publishing a test document containing the unicode character, but it appears I need tokens to cover the transaction. Is there a way I can get some tokens for testing purposes? Alternately, can you point me to a document containing the unicode character that has already been published that I can download?

**Comment by tzarebczan** [comment]
Hey @cbaumler , thanks for taking a look! You can grab some credits from https://lbry.tech/developer-program or join us at #dev (need to assign yourself this role) on our [Discord](https://chat.lbry.com)

I don't think such a document exists, but you can see what characters we support here: https://github.com/lbryio/lbry-sdk/pull/2473/files#diff-e5aa4edc5354f414c1abf2d21694020eR8

**Comment by cbaumler** [comment]
Hey @tzarebczan, thanks for the pointers. I managed to publish an rtf file containing unicode character \u2652 in the stream name. filename, and contents of the file. I used the cli. Unfortunately, I didn't observe the reported issue. Can you verify whether the issue is still reproducible and/or provide more details as to how to reproduce it?

**Comment by tzarebczan** [comment]
Can you try one with these characters in the claim name itself? It may be a windows only issue also.

The claim name I used was ♒

**Comment by mirgee** [comment]
@tzarebczan I tried on Linux, and it was published with no error.
