### ISSUE TITLE
Improve handling / error message when null values passed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2441]
If you pass a null value to something like thumbnail_url during publish, you end up with:

```2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice: Traceback (most recent call last):
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:   File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbry/extras/daemon/Daemon.py", line 584, in _process_rpc_call
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:     result = await result
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:   File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbry/extras/daemon/Daemon.py", line 2095, in jsonrpc_channel_update
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:     claim.channel.update(**kwargs)
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:   File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbry/schema/claim.py", line 127, in update
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:     setattr(attr, key[len(f'{field}_'):], kwargs.pop(key))
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:   File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbry/schema/attrs.py", line 199, in url
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:     self.message.url = url
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:   File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/google/protobuf/internal/python_message.py", line 662, in field_setter
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:     new_value = type_checker.CheckValue(new_value)
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:   File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/google/protobuf/internal/type_checkers.py", line 177, in CheckValue
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice:     raise TypeError(message)
2019-09-02 13:39:46.490 16053-16115/io.lbry.browser:service_lbrynet I/lbrynetservice: TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'bytes'>, <class 'str'>)```

**Comment by gpjacobs** [comment]
I'd like to take a shot at improving this, if that's ok.

**Comment by tzarebczan** [comment]
this was fixed in https://github.com/lbryio/lbry-sdk/pull/2543
