### ISSUE TITLE
migration error when trying to clean up database

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2453]
@jackrobison said this affects 0.19 clients, and possibly others. If the db is corrupt or can't startup, we should be able to default it back to a clean state.

```2019-09-08 20:58:11,024 INFO     lbry.extras.daemon.migrator.dbmigrator:35: failed to migrate database: duplicate column name: last_announced_time
2019-09-08 20:58:11,030 ERROR    lbry.extras.daemon.Component:62: Error setting up database
Traceback (most recent call last):
  File "lbry\extras\daemon\migrator\dbmigrator.py", line 33, in migrate_db
  File "lbry\extras\daemon\migrator\migrate6to7.py", line 9, in do_migration
sqlite3.OperationalError: duplicate column name: last_announced_time

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lbry\extras\daemon\Component.py", line 55, in _setup
  File "lbry\extras\daemon\Components.py", line 85, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbry\extras\daemon\migrator\dbmigrator.py", line 43, in migrate_db
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Abdul Jabbar.DESKTOP-LQRL6KM\\AppData\\Local\\lbry\\lbrynet\\lbrynet.sqlite' -> 'C:\\Users\\Abdul Jabbar.DESKTOP-LQRL6KM\\AppData\\Local\\lbry\\lbrynet\\rev_6_unmigrated_database.sqlite'
```
then
```
2019-09-08 20:58:15,592 ERROR    lbry.extras.daemon.Component:62: Error setting up blob_manager
Traceback (most recent call last):
  File "lbry\extras\daemon\Component.py", line 55, in _setup
  File "lbry\extras\daemon\Components.py", line 292, in start
  File "lbry\blob\blob_manager.py", line 86, in setup
AttributeError: 'NoneType' object has no attribute 'sync_missing_blobs'
2019-09-08 20:58:16,292 ERROR    lbry.extras.daemon.Component:62: Error setting up stream_manager
Traceback (most recent call last):
  File "lbry\extras\daemon\Component.py", line 55, in _setup
  File "lbry\extras\daemon\Components.py", line 428, in start
  File "lbry\stream\stream_manager.py", line 197, in start
  File "lbry\stream\stream_manager.py", line 136, in load_and_resume_streams_from_database
AttributeError: 'NoneType' object has no attribute 'update_manually_removed_files_since_last_run'```

**Comment by tzarebczan** [comment]
Here's another log from a recent upgrader: 
```020-04-03 00:32:32,218 INFO     lbry.extras.daemon.components:67: Loading databases
2020-04-03 00:32:32,228 INFO     lbry.extras.daemon.components:83: Upgrading your databases (revision 6 to 14)
2020-04-03 00:32:32,240 INFO     lbry.extras.daemon.daemon:442: detected internet connection is working
2020-04-03 00:32:32,355 INFO     lbry.extras.daemon.migrator.dbmigrator:57: successfully migrated the database from revision 6 to 7
2020-04-03 00:32:32,385 INFO     lbry.extras.daemon.migrator.dbmigrator:57: successfully migrated the database from revision 7 to 8
2020-04-03 00:32:32,440 INFO     lbry.extras.daemon.migrator.migrate8to9:29: Stream for descriptor 3bc4bc4fcff4a1753f7d0fe248531c57f9830fe2c627eadc6c8c09dad413e8db033d37a87bfac7bf3119537c6282c7fd is invalid, cleaning it up
2020-04-03 00:32:32,454 ERROR    lbry.extras.daemon.migrator.dbmigrator:43: failed to migrate database
Traceback (most recent call last):
  File "lbry\extras\daemon\migrator\dbmigrator.py", line 41, in migrate_db
  File "lbry\extras\daemon\migrator\migrate8to9.py", line 31, in do_migration
  File "lbry\extras\daemon\migrator\migrate8to9.py", line 45, in delete_stream
  File "ntpath.py", line 115, in join
  File "genericpath.py", line 149, in _check_arg_types
TypeError: join() argument must be str or bytes, not 'NoneType'
2020-04-03 00:32:32,571 ERROR    lbry.extras.daemon.component:62: Error setting up database
Traceback (most recent call last):
  File "lbry\extras\daemon\migrator\dbmigrator.py", line 41, in migrate_db
  File "lbry\extras\daemon\migrator\migrate8to9.py", line 31, in do_migration
  File "lbry\extras\daemon\migrator\migrate8to9.py", line 45, in delete_stream
  File "ntpath.py", line 115, in join
  File "genericpath.py", line 149, in _check_arg_types
TypeError: join() argument must be str or bytes, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lbry\extras\daemon\component.py", line 55, in _setup
  File "lbry\extras\daemon\components.py", line 85, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbry\extras\daemon\migrator\dbmigrator.py", line 51, in migrate_db
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\Thomas Schneider\\AppData\\Local\\lbry\\lbrynet\\lbrynet.sqlite' -> 'C:\\Users\\Thomas Schneider\\AppData\\Local\\lbry\\lbrynet\\rev_8_unmigrated_database.sqlite'```

**Comment by tzarebczan** [comment]
Here's another recent one: 
```2020-05-06 07:44:53,613 INFO lbry.extras.daemon.migrator.dbmigrator:57: successfully migrated the database from revision 4 to 5
2020-05-06 07:44:54,203 INFO lbry.extras.daemon.migrator.migrate5to6:218: migrated 131 blobs
2020-05-06 07:44:54,204 ERROR lbry.extras.daemon.migrator.dbmigrator:43: failed to migrate database
Traceback (most recent call last):
File "lbry\schema\claim.py", line 88, in from_bytes
File "lbry\schema\base.py", line 69, in from_bytes
google.protobuf.message.DecodeError: Could not determine message format version.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "site-packages\google\protobuf\internal\python_message.py", line 1083, in MergeFromString
File "site-packages\google\protobuf\internal\python_message.py", line 1105, in InternalParse
File "site-packages\google\protobuf\internal\decoder.py", line 181, in ReadTag
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "lbry\extras\daemon\migrator\dbmigrator.py", line 41, in migrate_db
File "lbry\extras\daemon\migrator\migrate5to6.py", line 311, in do_migration
File "lbry\extras\daemon\migrator\migrate5to6.py", line 78, in _wrapper
File "lbry\extras\daemon\migrator\migrate5to6.py", line 264, in _make_db
File "lbry\extras\daemon\migrator\migrate5to6.py", line 264, in <listcomp>
File "lbry\schema\claim.py", line 96, in from_bytes
File "lbry\schema\compat.py", line 56, in from_types_v1
File "site-packages\google\protobuf\message.py", line 185, in ParseFromString
File "site-packages\google\protobuf\internal\python_message.py", line 1089, in MergeFromString
google.protobuf.message.DecodeError: Truncated message.
2020-05-06 07:44:54,205 ERROR lbry.extras.daemon.component:62: Error setting up database
Traceback (most recent call last):
File "lbry\schema\claim.py", line 88, in from_bytes
File "lbry\schema\base.py", line 69, in from_bytes
google.protobuf.message.DecodeError: Could not determine message format version.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "site-packages\google\protobuf\internal\python_message.py", line 1083, in MergeFromString
File "site-packages\google\protobuf\internal\python_message.py", line 1105, in InternalParse
File "site-packages\google\protobuf\internal\decoder.py", line 181, in ReadTag
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "lbry\extras\daemon\migrator\dbmigrator.py", line 41, in migrate_db
File "lbry\extras\daemon\migrator\migrate5to6.py", line 311, in do_migration
File "lbry\extras\daemon\migrator\migrate5to6.py", line 78, in _wrapper
File "lbry\extras\daemon\migrator\migrate5to6.py", line 264, in _make_db
File "lbry\extras\daemon\migrator\migrate5to6.py", line 264, in <listcomp>
File "lbry\schema\claim.py", line 96, in from_bytes
File "lbry\schema\compat.py", line 56, in from_types_v1
File "site-packages\google\protobuf\message.py", line 185, in ParseFromString
File "site-packages\google\protobuf\internal\python_message.py", line 1089, in MergeFromString
google.protobuf.message.DecodeError: Truncated message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "lbry\extras\daemon\component.py", line 55, in _setup
File "lbry\extras\daemon\components.py", line 85, in start
File "concurrent\futures\thread.py", line 57, in run
File "lbry\extras\daemon\migrator\dbmigrator.py", line 51, in migrate_db
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Shawn Gordon\\AppData\\Local\\lbry\\lbrynet\\lbrynet.sqlite' -> 'C:\\Users\\Shawn Gordon\\AppData\\Local\\lbry\\lbrynet\\rev_5_unmigrated_database.sqlite'
2020-05-06 07:44:56,187 WARNING lbry.extras.daemon.components:418: upnp discovery failed: M-SEARCH for 10.131.250.71:1900 timed out
```
