### ISSUE TITLE
tuple issues / bad argument to internal function 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2457]
Got this after running @jackrobison 's latest changes: 

```2019-09-12 16:36:50,240 INFO     lbry.dht.node:118: DHT node listening on UDP 0.0.0.0:4400
2019-09-12 16:36:50,327 INFO     torba.client.basenetwork:305: connected to spv1.lbry.com:50001
2019-09-12 16:36:50,327 INFO     torba.client.basenetwork:175: Switching to SPV wallet server: spv1.lbry.com:50001
2019-09-12 16:36:50,329 INFO     torba.client.baseledger:291: Subscribing and updating accounts.
2019-09-12 16:36:50,358 INFO     torba.client.basenetwork:179: Subscribed to headers: spv1.lbry.com:50001
2019-09-12 16:36:50,379 INFO     torba.client.baseledger:135: lbc_mainnet: added BlockHeightEvent(height=632569, change=61) header blocks, final height 632569
2019-09-12 16:36:50,810 INFO     lbry.extras.daemon.Daemon:396: detected internet connection is working
2019-09-12 16:36:53,403 INFO     lbry.extras.daemon.Daemon:842: Get version info: {"processor": "AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD", "python_version": "3.7.2", "platform": "Windows-10-10.0.18362-SP0", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.40.1", "torba_version": "0.5.7", "build": "dev"}
2019-09-12 16:36:53,412 ERROR    torba.client.basedatabase:69: Error running transaction:
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 65, in __run_transaction
    result = fun(self.connection, *args, **kwargs)  # type: ignore
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\storage.py", line 414, in _sync_blobs
    for (blob_hash, ) in transaction.execute("select blob_hash from blob where status='finished'")
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\storage.py", line 413, in <listcomp>
    (blob_hash, )
SystemError: g:\a\3\s\objects\tupleobject.c:168: bad argument to internal function
2019-09-12 16:36:53,436 ERROR    torba.client.basedatabase:69: Error running transaction:
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 65, in __run_transaction
    result = fun(self.connection, *args, **kwargs)  # type: ignore
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 51, in <lambda>
    return self.run(lambda conn: conn.execute(sql, parameters).fetchall())
SystemError: g:\a\3\s\objects\tupleobject.c:168: bad argument to internal function
2019-09-12 16:36:53,595 WARNING  torba.client.basedatabase:71: rolled back
2019-09-12 16:36:53,630 WARNING  torba.client.basedatabase:71: rolled back
2019-09-12 16:36:53,708 ERROR    lbry.extras.daemon.Component:62: Error setting up blob_manager
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Component.py", line 55, in _setup
    result = await self.start()
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Components.py", line 292, in start
    return await self.blob_manager.setup()
  File "c:\users\thoma\documents\lbry\lbry\lbry\blob\blob_manager.py", line 86, in setup
    to_add = await self.storage.sync_missing_blobs(in_blobfiles_dir)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 59, in <lambda>
    self.executor, lambda: self.__run_transaction(fun, *args, **kwargs)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 65, in __run_transaction
    result = fun(self.connection, *args, **kwargs)  # type: ignore
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\storage.py", line 414, in _sync_blobs
    for (blob_hash, ) in transaction.execute("select blob_hash from blob where status='finished'")
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\storage.py", line 413, in <listcomp>
    (blob_hash, )
SystemError: g:\a\3\s\objects\tupleobject.c:168: bad argument to internal function
2019-09-12 16:36:53,751 ERROR    lbry.extras.daemon.Component:62: Error setting up wallet
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Component.py", line 55, in _setup
    result = await self.start()
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Components.py", line 262, in start
    await self.wallet_manager.start()
  File "c:\users\thoma\documents\lbry\torba\torba\client\basemanager.py", line 73, in start
    l.start() for l in self.ledgers.values()
  File "c:\users\thoma\documents\lbry\lbry\lbry\wallet\ledger.py", line 86, in start
    await asyncio.gather(*(a.save_max_gap() for a in self.accounts))
  File "c:\users\thoma\documents\lbry\lbry\lbry\wallet\account.py", line 72, in save_max_gap
    gap = await self.get_max_gap()
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseaccount.py", line 413, in get_max_gap
    receiving_gap = await self.receiving.get_max_gap()
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseaccount.py", line 118, in get_max_gap
    addresses = await self._query_addresses(order_by="position ASC")
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 571, in get_addresses
    addresses = await self.select_addresses(', '.join(cols), **constraints)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 566, in select_addresses
    "SELECT {} FROM pubkey_address".format(cols), **constraints
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 59, in <lambda>
    self.executor, lambda: self.__run_transaction(fun, *args, **kwargs)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 65, in __run_transaction
    result = fun(self.connection, *args, **kwargs)  # type: ignore
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 51, in <lambda>
    return self.run(lambda conn: conn.execute(sql, parameters).fetchall())
SystemError: g:\a\3\s\objects\tupleobject.c:168: bad argument to internal function
Task exception was never retrieved
future: <Task finished coro=<Component._setup() done, defined at c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Component.py:53> exception=SystemError('g:\\a\\3\\s\\objects\\tupleobject.c:168: bad argument to internal function')>
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Component.py", line 63, in _setup
    raise err
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Component.py", line 55, in _setup
    result = await self.start()
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Components.py", line 292, in start
    return await self.blob_manager.setup()
  File "c:\users\thoma\documents\lbry\lbry\lbry\blob\blob_manager.py", line 86, in setup
    to_add = await self.storage.sync_missing_blobs(in_blobfiles_dir)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 59, in <lambda>
    self.executor, lambda: self.__run_transaction(fun, *args, **kwargs)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 65, in __run_transaction
    result = fun(self.connection, *args, **kwargs)  # type: ignore
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\storage.py", line 414, in _sync_blobs
    for (blob_hash, ) in transaction.execute("select blob_hash from blob where status='finished'")
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\storage.py", line 413, in <listcomp>
    (blob_hash, )
SystemError: g:\a\3\s\objects\tupleobject.c:168: bad argument to internal function
Task exception was never retrieved
future: <Task finished coro=<Component._setup() done, defined at c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Component.py:53> exception=SystemError('g:\\a\\3\\s\\objects\\tupleobject.c:168: bad argument to internal function')>
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Component.py", line 63, in _setup
    raise err
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Component.py", line 55, in _setup
    result = await self.start()
  File "c:\users\thoma\documents\lbry\lbry\lbry\extras\daemon\Components.py", line 262, in start
    await self.wallet_manager.start()
  File "c:\users\thoma\documents\lbry\torba\torba\client\basemanager.py", line 73, in start
    l.start() for l in self.ledgers.values()
  File "c:\users\thoma\documents\lbry\lbry\lbry\wallet\ledger.py", line 86, in start
    await asyncio.gather(*(a.save_max_gap() for a in self.accounts))
  File "c:\users\thoma\documents\lbry\lbry\lbry\wallet\account.py", line 72, in save_max_gap
    gap = await self.get_max_gap()
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseaccount.py", line 413, in get_max_gap
    receiving_gap = await self.receiving.get_max_gap()
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseaccount.py", line 118, in get_max_gap
    addresses = await self._query_addresses(order_by="position ASC")
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 571, in get_addresses
    addresses = await self.select_addresses(', '.join(cols), **constraints)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 566, in select_addresses
    "SELECT {} FROM pubkey_address".format(cols), **constraints
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 59, in <lambda>
    self.executor, lambda: self.__run_transaction(fun, *args, **kwargs)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 65, in __run_transaction
    result = fun(self.connection, *args, **kwargs)  # type: ignore
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 51, in <lambda>
    return self.run(lambda conn: conn.execute(sql, parameters).fetchall())
SystemError: g:\a\3\s\objects\tupleobject.c:168: bad argument to internal function
2019-09-12 16:36:53,789 INFO     lbry.extras.daemon.Components:386: Started blob announcer
2019-09-12 16:36:53,789 INFO     lbry.extras.daemon.Components:448: start blob server
Collapse```

**Comment by tzarebczan** [comment]
This is now fixed.
