### ISSUE TITLE
get_transaction_history can raise MemoryError in 0.42.0

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry-sdk#2504]
```
Traceback (most recent call last):
  File "lbry\extras\daemon\Daemon.py", line 584, in _process_rpc_call
  File "lbry\extras\daemon\Daemon.py", line 137, in maybe_paginate
  File "lbry\wallet\ledger.py", line 148, in get_transaction_history
  File "torba\client\basedatabase.py", line 456, in get_transactions
  File "torba\client\basedatabase.py", line 449, in select_transactions
  File "concurrent\futures\thread.py", line 57, in run
  File "torba\client\basedatabase.py", line 62, in <lambda>
  File "torba\client\basedatabase.py", line 68, in __run_transaction
  File "torba\client\basedatabase.py", line 50, in <lambda>
MemoryError
```

**Comment by lyoshenka** [comment]
not gonna fix problems with 0.42
