### ISSUE TITLE
Mass abandoning supports / support create times out

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-sdk#2528]
When trying to abandon a support (for example this one with 1634 transactions), the SDK fails:

```
1d/1z [lbry@ytsync4:~] 1m18s 148 $ /opt/lbry/lbrynet support abandon --blocking --claim_id=173078c44b5b7ec794f8bf4a341c7b5a346b6a8e
Traceback (most recent call last):
  File "lbry/extras/cli.py", line 317, in <module>
  File "lbry/extras/cli.py", line 307, in main
  File "asyncio/base_events.py", line 573, in run_until_complete
  File "lbry/extras/cli.py", line 32, in execute_command
  File "site-packages/aiohttp/client.py", line 1005, in __aenter__
  File "site-packages/aiohttp/client.py", line 497, in _request
  File "site-packages/aiohttp/client_reqrep.py", line 857, in start
  File "site-packages/aiohttp/helpers.py", line 585, in __exit__
concurrent.futures._base.TimeoutError
[2660] Failed to execute script cli
```

this also never returns to the JSON RPC, which means that if the call is invoked over HTTP, the client will remain hanging until the timeout is reached.

**Comment by tzarebczan** [comment]
Users and youtube sync also have the same problem with support create. This generally happens on larger wallets/transactions.
