### ISSUE TITLE
Error while advancing transaction in new block / sql error in trending

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2610]
Getting this on master now. Additional debugging shows: 
```
Traceback (most recent call last):
  File "/home/tom/lbry/lbry/lbry/wallet/server/db/trending.py", line 47, in finalize
    return (self.last - self.mean) / (self.standard_deviation or 1)
  File "/home/tom/lbry/lbry/lbry/wallet/server/db/trending.py", line 42, in standard_deviation
    return sqrt((self.power / self.count) - self.mean ** 2)
ValueError: math domain error
ERROR:torba.server.block_processor.LBRYBlockProcessor:Error while advancing transaction in new block.
Traceback (most recent call last):

```

```
      0.04mins calculate_trending
====================================================================================================
INFO:torba.server.block_processor.LBRYBlockProcessor:our height: 663,132 daemon: 670,775 UTXOs 849MB hist 148MB
INFO:torba.server.block_processor.LBRYBlockProcessor:our height: 665,341 daemon: 670,775 UTXOs 854MB hist 155MB
INFO:torba.server.block_processor.LBRYBlockProcessor:our height: 666,640 daemon: 670,775 UTXOs 834MB hist 164MB
INFO:torba.server.block_processor.LBRYBlockProcessor:our height: 667,245 daemon: 670,775 UTXOs 835MB hist 167MB
Traceback (most recent call last):
  File "/home/tom/lbry/lbry/lbry/wallet/server/db/trending.py", line 47, in finalize
    return (self.last - self.mean) / (self.standard_deviation or 1)
  File "/home/tom/lbry/lbry/lbry/wallet/server/db/trending.py", line 42, in standard_deviation
    return sqrt((self.power / self.count) - self.mean ** 2)
ValueError: math domain error
ERROR:torba.server.block_processor.LBRYBlockProcessor:Error while advancing transaction in new block.
Traceback (most recent call last):
  File "/home/tom/lbry/lbry/lbry/wallet/server/block_processor.py", line 76, in advance_blocks
    self.timer.run(super().advance_blocks, blocks)
  File "/home/tom/lbry/lbry/lbry/wallet/server/block_processor.py", line 30, in run
    return func(*args, **kwargs)
  File "/home/tom/lbry/torba/torba/server/block_processor.py", line 378, in advance_blocks
    height, block.transactions, self.coin.electrum_header(block.header, height)
  File "/home/tom/lbry/lbry/lbry/wallet/server/block_processor.py", line 92, in advance_txs
    timer.run(self.sql.advance_txs, height, txs, header, self.daemon.cached_height(), forward_timer=True)
  File "/home/tom/lbry/lbry/lbry/wallet/server/block_processor.py", line 28, in run
    return func(*args, **kwargs, timer=t)
  File "/home/tom/lbry/lbry/lbry/wallet/server/db/writer.py", line 752, in advance_txs
    r(calculate_trending, self.db, height, daemon_height)
  File "/home/tom/lbry/lbry/lbry/wallet/server/block_processor.py", line 30, in run
    return func(*args, **kwargs)
  File "/home/tom/lbry/lbry/lbry/wallet/server/db/trending.py", line 96, in calculate_trending
    """)
sqlite3.OperationalError: user-defined aggregate's 'finalize' method raised error


```

**Comment by tzarebczan** [comment]
This is no longer happening, closing.
