### ISSUE TITLE
too many sql variables on file list + large page size

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2663]
The dreaded sqlite variables error is back. It works fine on default page 1, but errors when running it with 999 or higher. 

```c:\Program Files\LBRY\resources\static\daemon>lbrynet file list --page_size=9999
{
  "code": -32500,
  "data": [
    "Traceback (most recent call last):",
    "  File \"lbry\\extras\\daemon\\Daemon.py\", line 591, in _process_rpc_call",
    "  File \"lbry\\extras\\daemon\\Daemon.py\", line 1821, in jsonrpc_file_list",
    "  File \"lbry\\wallet\\database.py\", line 104, in get_purchases",
    "  File \"lbry\\wallet\\database.py\", line 80, in get_transactions",
    "  File \"torba\\client\\basedatabase.py\", line 458, in get_transactions",
    "  File \"torba\\client\\basedatabase.py\", line 451, in select_transactions",
    "  File \"concurrent\\futures\\thread.py\", line 57, in run",
    "  File \"torba\\client\\basedatabase.py\", line 63, in <lambda>",
    "  File \"torba\\client\\basedatabase.py\", line 70, in __run_transaction",
    "  File \"torba\\client\\basedatabase.py\", line 51, in <lambda>",
    "sqlite3.OperationalError: too many SQL variables",
    ""
  ],
  "message": "Error calling file_list with args {'reverse': False, 'page_size': 9999}\ntoo many SQL variables"
}
```

**Comment by tzarebczan** [comment]
I'm getting this on a 2nd pc now with 1000 files: ```Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry-sdk\lbry\extras\daemon\daemon.py", line 655, in _process_rpc_call
    result = await result
  File "c:\users\thoma\documents\lbry-sdk\lbry\extras\daemon\daemon.py", line 1931, in jsonrpc_file_list
    purchased_claim_id__in=[s.claim_id for s in paginated['items']]
  File "c:\users\thoma\documents\lbry-sdk\lbry\wallet\database.py", line 773, in get_purchases
    return [tx.outputs[0] for tx in await self.get_transactions(**constraints)]
  File "c:\users\thoma\documents\lbry-sdk\lbry\wallet\database.py", line 512, in get_transactions
    **constraints
  File "c:\users\thoma\documents\lbry-sdk\lbry\wallet\database.py", line 503, in select_transactions
    *query(f"SELECT {cols} FROM tx", **constraints)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\thoma\documents\lbry-sdk\lbry\wallet\database.py", line 66, in <lambda>
    self.executor, lambda: self.__run_transaction(fun, *args, **kwargs)
  File "c:\users\thoma\documents\lbry-sdk\lbry\wallet\database.py", line 73, in __run_transaction
    result = fun(self.connection, *args, **kwargs)  # type: ignore
  File "c:\users\thoma\documents\lbry-sdk\lbry\wallet\database.py", line 54, in <lambda>
    return self.run(lambda conn: conn.execute(sql, parameters).fetchall())
sqlite3.OperationalError: too many SQL variables```
