### ISSUE TITLE
Larger channels/queries time out on wallet server (apsw)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2671]
Since the apsw channel, larger channels/queries now time out differently. 

sample: 
```
{"jsonrpc":"2.0","method":"claim_search","params":{"channel":"lbry://@davidpakman#7","page":1,"page_size":20,"valid_channel_signature":true,"order_by":["release_time"]},"id":1576097496620}
```

```
{
  "error": {
    "code": -32500,
    "data": [
      "Traceback (most recent call last):",
      "  File \"lbry\\extras\\daemon\\Daemon.py\", line 596, in _process_rpc_call",
      "  File \"lbry\\extras\\daemon\\Daemon.py\", line 2251, in jsonrpc_claim_search",
      "  File \"lbry\\wallet\\ledger.py\", line 99, in claim_search",
      "  File \"lbry\\wallet\\ledger.py\", line 59, in _inflate_outputs",
      "  File \"torba\\client\\basenetwork.py\", line 61, in send_request",
      "  File \"torba\\client\\basenetwork.py\", line 77, in _send_request",
      "  File \"torba\\client\\basenetwork.py\", line 70, in _send_request",
      "  File \"asyncio\\tasks.py\", line 442, in wait_for",
      "  File \"torba\\rpc\\session.py\", line 490, in send_request",
      "torba.rpc.jsonrpc.RPCError: (-32603, 'query failed to execute')",
      ""
    ],
    "message": "Error calling claim_search with args {'channel': 'lbry://@Gutenberg#a', 'page': 1, 'page_size': 20, 'valid_channel_signature': True, 'order_by': ['release_time']}\n(-32603, 'query failed to execute')"
  },
  "jsonrpc": "2.0"
}
```
```
ERROR:torba.server.session.LBRYSessionManager:failed running query
Traceback (most recent call last):
  File "/home/lbry/lbry/lbry/wallet/server/db/reader.py", line 166, in execute_query
    return context.db.cursor().execute(sql, values).fetchall()
  File "src/cursor.c", line 236, in resetcursor
apsw.InterruptError: InterruptError: interrupted```

**Comment by tzarebczan** [comment]
This was fixed
