### ISSUE TITLE
Cannot claim_search by languages. 

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-sdk#2797]
```
curl -d'{"method": "claim_search", "params": {"any_tags": ["chillstep"], "any_languages": ["en"]}}' http://localhost:5279/
{
  "error": {
    "code": -32500,
    "data": {
      "args": [],
      "command": "claim_search",
      "kwargs": {
        "any_languages": [
          "en"
        ],
        "any_tags": [
          "chillstep"
        ]
      },
      "name": "RPCError",
      "traceback": [
        "Traceback (most recent call last):",
        "  File \"lbry/extras/daemon/daemon.py\", line 653, in _process_rpc_call",
        "  File \"lbry/extras/daemon/daemon.py\", line 2329, in jsonrpc_claim_search",
        "  File \"lbry/wallet/ledger.py\", line 674, in claim_search",
        "  File \"lbry/wallet/ledger.py\", line 633, in _inflate_outputs",
        "  File \"lbry/wallet/network.py\", line 75, in send_request",
        "  File \"lbry/wallet/network.py\", line 71, in send_request",
        "  File \"lbry/wallet/rpc/session.py\", line 462, in send_request",
        "lbry.wallet.rpc.jsonrpc.RPCError: (-32603, 'query failed to execute')",
        ""
      ]
    },
    "message": "(-32603, 'query failed to execute')"
  },
  "jsonrpc": "2.0"
}

```

```
ERROR:lbry.wallet.server.session.LBRYSessionManager:failed running query
wallet_server_1  | Traceback (most recent call last):
wallet_server_1  |   File "/home/lbry/lbry/wallet/server/db/reader.py", line 200, in execute_query
wallet_server_1  |     for row in c.execute(sql, values):
wallet_server_1  |   File "src/cursor.c", line 1019, in APSWCursor_execute.sqlite3_prepare
wallet_server_1  |   File "src/statementcache.c", line 386, in sqlite3_prepare
wallet_server_1  | apsw.SQLError: SQLError: no such table: language
wallet_server_1  | INFO:aiohttp.access:18.222.104.49 [12/Feb/2020:23:13:33 +0000] "GET /metrics HTTP/1.1" 200 31186 "-" "Prometheus/2.15.2"
```

**Comment by kauffj** [comment]
add language to claim, save language during sync, add index

**Comment by kauffj** [comment]
add duplicates of common indexes but with language
