### ISSUE TITLE
Address_unused returns index error if wallet not fully loaded

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2837]
This happens randomly on lbry.tv when wallet add is used to create a new wallet, and the app calls wallet unused to get an address.  The SDK should wait til the wallet is finished creating or add a blocking command to it. 

```18:31:44
2020-02-12 18:31:44,191 ERROR lbry.extras.daemon.daemon:659: error handling api request
18:31:44
Traceback (most recent call last):
18:31:44
File "lbry/extras/daemon/daemon.py", line 653, in _process_rpc_call
18:31:44
File "lbry/wallet/account.py", line 103, in get_or_create_usable_address
18:31:44
IndexError: list index out of range```

**Comment by kauffj** [comment]
@eukreign is this fixed in rewrite?
