### ISSUE TITLE
shutdown issues / wallet fails to start: no such table: pubkey_address

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#3075]
```2020-10-27 13:34:25,428 ERROR    lbry.extras.daemon.component:62: Error setting up wallet
Traceback (most recent call last):
  File "lbry/extras/daemon/component.py", line 55, in _setup
  File "lbry/extras/daemon/components.py", line 166, in start
  File "lbry/wallet/manager.py", line 80, in start
  File "lbry/wallet/ledger.py", line 334, in start
  File "lbry/wallet/database.py", line 1257, in release_all_outputs
  File "lbry/wallet/database.py", line 170, in execute_fetchall
  File "lbry/wallet/database.py", line 165, in _execute_fetch
  File "lbry/wallet/database.py", line 199, in run
  File "concurrent/futures/thread.py", line 57, in run
  File "lbry/wallet/database.py", line 199, in <lambda>
  File "lbry/wallet/database.py", line 212, in __run_transaction
  File "lbry/wallet/database.py", line 165, in <lambda>
sqlite3.OperationalError: no such table: txo
2020-10-27 13:34:25,429 INFO     lbry.extras.daemon.components:355: Starting the file manager
2020-10-27 13:34:25,429 INFO     lbry.extras.daemon.components:415: start blob server
2020-10-27 13:34:25,430 INFO     lbry.extras.daemon.components:317: Started blob announcer
2020-10-27 13:34:25,430 ERROR    lbry.wallet.database:216: Error running transaction:
Traceback (most recent call last):
  File "lbry/wallet/database.py", line 212, in __run_transaction
  File "lbry/wallet/database.py", line 165, in <lambda>
sqlite3.OperationalError: no such table: pubkey_address****
```

**Comment by tzarebczan** [comment]
I was able to repro this and it happens when a DB is shutdown after a TX is confirmed, and the wal/whl files don't get cleared. On YT sync, we don't copy those, and only restore blockchain.db. 

This situation is probably what's also causing other shutdown issues and resyncing on YT sync.

**Comment by tzarebczan** [comment]
Repro:
start fresh wallet
send funds
wait for tx confirmation
shutdown
notice whl/wal files

Jack mentioned it probably needs to kill all queries before shutting down.
