### ISSUE TITLE
startup prevented - OSError: unknown blob length

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#3185]
2021-02-04 06:32:27,498 INFO     lbry.blob_exchange.server:176: Blob server listening on TCP 0.0.0.0:3333
2021-02-04 06:32:28,629 WARNING  lbry.blob.blob_file:122: Got an invalid length. Previous length: None, Invalid length: 2384926
2021-02-04 06:32:28,630 ERROR    lbry.extras.daemon.component:62: Error setting up file_manager
Traceback (most recent call last):
  File "lbry\extras\daemon\component.py", line 55, in _setup
  File "lbry\extras\daemon\components.py", line 367, in start
  File "lbry\file\file_manager.py", line 46, in start
  File "lbry\stream\stream_manager.py", line 195, in start
  File "lbry\file\source_manager.py", line 72, in start
  File "lbry\stream\stream_manager.py", line 132, in initialize_from_database
  File "lbry\stream\stream_manager.py", line 91, in recover_streams
  File "lbry\stream\stream_manager.py", line 80, in recover_stream
  File "lbry\stream\descriptor.py", line 292, in recover
  File "lbry\stream\descriptor.py", line 168, in make_sd_blob
  File "lbry\blob\writer.py", line 36, in write
OSError: unknown blob length

**Comment by tzarebczan** [comment]
Happened again: 
```
2021-08-18 15:15:51,293 WARNING  lbry.blob.blob_file:122: Got an invalid length. Previous length: None, Invalid length: 3557581
2021-08-18 15:15:51,294 ERROR    lbry.extras.daemon.component:62: Error setting up file_manager
Traceback (most recent call last):
  File "lbry/extras/daemon/component.py", line 55, in _setup
  File "lbry/extras/daemon/components.py", line 371, in start
  File "lbry/file/file_manager.py", line 46, in start
  File "lbry/stream/stream_manager.py", line 195, in start
  File "lbry/file/source_manager.py", line 72, in start
  File "lbry/stream/stream_manager.py", line 132, in initialize_from_database
  File "lbry/stream/stream_manager.py", line 91, in recover_streams
  File "lbry/stream/stream_manager.py", line 80, in recover_stream
  File "lbry/stream/descriptor.py", line 292, in recover
  File "lbry/stream/descriptor.py", line 168, in make_sd_blob
  File "lbry/blob/writer.py", line 36, in write
OSError: unknown blob length
```
