### ISSUE TITLE
client reconnection issue (new seen on cluster this week)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#3234]
Was trying to subscribe + reconnect and would fail. 

```
2021-03-10 19:08:41,035 ERROR    lbry.extras.daemon.daemon:717: error handling api request
│ Traceback (most recent call last):
│   File "lbry/extras/daemon/daemon.py", line 709, in _process_rpc_call
│   File "lbry/extras/daemon/daemon.py", line 2498, in jsonrpc_claim_search
│   File "lbry/wallet/ledger.py", line 875, in claim_search
│   File "lbry/wallet/network.py", line 425, in claim_search
│   File "lbry/wallet/network.py", line 340, in rpc
│ ConnectionError: Attempting to send rpc request when connection is not available.```

**Comment by tzarebczan** [comment]
The 0.101.1 update which had concurrency limits didn't help. We need to prioritize this asap.

**Comment by tzarebczan** [comment]
Can the SDK just shutdown when this happens? It needs a reboot, and there's no recovering from it from what I understand.

**Comment by tzarebczan** [comment]
This is also similar and needs a reboot, but for local claim data (one or more users generally affected):

```022-04-06 02:57:44,925 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: collection_list                                                                                                                                                                                                                      ││ 2022-04-06 02:57:54,545 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: resolve                                                                                                                                                                                                                              ││ 2022-04-06 02:57:58,837 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: collection_list                                                                                                                                                                                                                      ││ 2022-04-06 02:57:58,886 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: channel_list                                                                                                                                                                                                                         ││ 2022-04-06 02:57:58,914 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: resolve                                                                                                                                                                                                                              ││ 2022-04-06 02:58:01,947 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: channel_list                                                                                                                                                                                                                         ││ 2022-04-06 02:58:02,087 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: collection_list                                                                                                                                                                                                                      ││ 2022-04-06 02:58:02,144 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: resolve                                                                                                                                                                                                                              ││ 2022-04-06 02:58:03,285 INFO     lbry.wallet.ledger:150: lbc_mainnet: added BlockHeightEvent(height=1138877, change=1) header blocks, final height 1138877                                                                                                                                                                   ││ 2022-04-06 02:58:13,348 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: resolve                                                                                                                                                                                                                              ││ 2022-04-06 02:58:16,631 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: resolve                                                                                                                                                                                                                              ││ 2022-04-06 02:58:17,719 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: collection_list                                                                                                                                                                                                                      ││ 2022-04-06 02:58:17,734 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: channel_list                                                                                                                                                                                                                         ││ 2022-04-06 02:58:19,215 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: address_unused                                                                                                                                                                                                                       ││ 2022-04-06 02:58:37,923 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: resolve                                                                                                                                                                                                                              ││ 2022-04-06 02:58:43,586 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: channel_list                                                                                                                                                                                                                         ││ 2022-04-06 02:58:43,592 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: collection_list                                                                                                                                                                                                                      ││ 2022-04-06 02:58:44,258 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: resolve                                                                                                                                                                                                                              ││ 2022-04-06 02:58:44,692 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: resolve                                                                                                                                                                                                                              ││ 2022-04-06 02:58:47,916 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: address_unused                                                                                                                                                                                                                       ││ 2022-04-06 02:59:21,177 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: resolve                                                                                                                                                                                                                              ││ 2022-04-06 02:59:27,396 INFO     lbry.extras.daemon.daemon:697: cancelled API call for: resolve           ```
