### ISSUE TITLE
Handle exchange errors in logs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#3287]
No need to spam logs with this: 
```
</body>
</html>
2021-04-30 09:49:03,443 INFO     lbry.wallet.server.udp:191: closed udp spv server selection client
2021-04-30 09:51:34,944 INFO     lbry.wallet.ledger:150: lbc_mainnet: added BlockHeightEvent(height=954033, change=1) header blocks, final height 954033
2021-04-30 09:51:58,684 WARNING  lbry.extras.daemon.exchange_rate_manager:89: Could not parse exchange rate response from hotbit: <html>
<head>
<meta charset="utf-8">
<title>Connect time out</title>
2021-04-30 11:37:06,252 WARNING  lbry.extras.daemon.exchange_rate_manager:89: Could not parse exchange rate response from hotbit: <html>
<head>
<meta charset="utf-8">
<title>Connect time out</title>
</head>
<body>
We have a problem,please hold on <div class="cf-error-details cf-error-522">
  <h1>Connection timed out</h1>
  <p>The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.</p>
  <ul>
    <li>Ray ID: 6481d8b21ee55766</li>
    <li>Your IP address: 26xxa9fa</li>
    <li>Error reference number: 522</li>
    <li>Cloudflare Location: Ashburn</li>
  </ul>
</div>
</body>
</html> (edited) 
```

**Comment by tzarebczan** [comment]
More: 
````
2021-07-02 12:11:32,490 ERROR    lbry.extras.daemon.exchange_rate_manager:96: Exchange rate error (BTCLBC from UPbit):
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry-sdk\lbry\extras\daemon\exchange_rate_manager.py", line 77, in get_rate
    rate = self.get_rate_from_response(data)
  File "c:\users\thoma\documents\lbry-sdk\lbry\extras\daemon\exchange_rate_manager.py", line 189, in get_rate_from_response
    if len(json_response) != 1 or 'trade_price' not in json_response[0]:
KeyError: 0
```

**Comment by belikor** [comment]
I remember seeing a lot of messages like in the first post, but I haven't seen them in a while, so maybe that is no longer a problem with the newest sdk (0.99 or 0.100).

The second type of error, about the UPbit exchange, is handled by #3361.
