### ISSUE TITLE
Start-up fails on linux, if ~/.config/user-dirs.dirs doesn't have XDG_DOWNLOAD_DIR set

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-sdk#3318]
If the file `~/.config/user-dirs.dirs` **exists**, but doesn't have line `XDG_DOWNLOAD_DIR=<dir>` the start-up fails with the following error. 
```
Daemon: [13852] Failed to execute script cli

Daemon: Traceback (most recent call last):
  File "lbry/extras/cli.py", line 336, in <module>
  File "lbry/extras/cli.py", line 293, in main
  File "lbry/conf.py", line 439, in create_from_arguments
  File "lbry/conf.py", line 657, in __init__
  File "lbry/conf.py", line 669, in set_default_paths
  File "lbry/conf.py", line 717, in get_linux_directories
UnboundLocalError: local variable 'download_dir' referenced before assignment
```

**Comment by cristi-zz** [comment]
Current master, works.  (commit 21c71bfac1d7d58d129956910709e5687ec02334)
