### ISSUE TITLE
tests.unit.lbrynet_daemon.test_allowed_origin.TestAccessHeaders raises OSError

### ISSUE THREAD

**Issue by 7astro7** [lbryio/lbry-sdk#3321]
This seems like an edge case and while uncertain whether it should be ticketed as an issue, I think it makes sense to get feedback on this considering 339 of the 343 tests passed and 3 were skipped. The kernel is 5.12.8-arch1-1 and for context the /etc/hosts file includes only these three lines: 
127.0.0.1 localhost
::1 	  localhost    
127.0.1.1 X.localdomain X

................................................
======================================================================
ERROR: test_headers (tests.unit.lbrynet_daemon.test_allowed_origin.TestAccessHeaders)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lbry/lbry-sdk/lbry/extras/daemon/daemon.py", line 470, in start
    await rpc_site.start()
  File "/lbry/lbry-sdk/lbry-venv/lib/python3.7/site-packages/aiohttp/web_runner.py", line 102, in start
    reuse_port=self._reuse_port)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1389, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 99] error while attempting to bind on address ('::1', 5299, 0, 0): cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lbry/lbry-sdk/lbry/testcase.py", line 135, in run
    self.loop.run_until_complete(self.asyncSetUp())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1778, in _run_once
    handle._run()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/lbry/lbry-sdk/tests/unit/lbrynet_daemon/test_allowed_origin.py", line 79, in asyncSetUp
    await self.daemon.start()
  File "/lbry/lbry-sdk/lbry/extras/daemon/daemon.py", line 475, in start
    raise SystemExit()
SystemExit

----------------------------------------------------------------------
Ran 343 tests in 57.703s

FAILED (errors=1, skipped=3)

**Comment by lyoshenka** [comment]
Thanks for the detailed report @7astro7. We'll check it out soon.

Can we show you some [https://lbry.com/faq/appreciation](appreciation)?

**Comment by belikor** [comment]
I'm not sure this is a real problem. This message appears only if the `lbrynet` daemon is already running, but it doesn't if it's not running.

Start the daemon.
```
python lbry/extras/cli.py start
```

In another terminal, run the test.
```
python -m unittest tests.unit.lbrynet_daemon.test_allowed_origin.TestAccessHeaders
```

```
======================================================================
ERROR: test_headers (tests.unit.lbrynet_daemon.test_allowed_origin.TestAccessHeaders)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/git/lbry-sdk/lbry/extras/daemon/daemon.py", line 480, in start
    await streaming_site.start()
  File "/opt/git/lbry-sdk/lbry-venv/lib/python3.7/site-packages/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1389, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 5280): address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/git/lbry-sdk/lbry/testcase.py", line 135, in run
    self.loop.run_until_complete(self.asyncSetUp())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1778, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/git/lbry-sdk/tests/unit/lbrynet_daemon/test_allowed_origin.py", line 79, in asyncSetUp
    await self.daemon.start()
  File "/opt/git/lbry-sdk/lbry/extras/daemon/daemon.py", line 486, in start
    raise SystemExit()
SystemExit

----------------------------------------------------------------------
Ran 1 test in 0.122s

FAILED (errors=1)
```

But if the daemon is not running, the test passes successfully.
```
python lbry/extras/cli.py stop
```

```
python -m unittest tests.unit.lbrynet_daemon.test_allowed_origin.TestAccessHeaders
```

```
.
----------------------------------------------------------------------
Ran 1 test in 0.694s

OK
```

**Comment by 7astro7** [comment]
Alright, I wasn't sure so will close this issue. @lyoshenka the kind offer is appreciation enough dwai
