### ISSUE TITLE
test_reorg_change_claim_height: lbry.wallet.orchstr8.node - ERROR - failed to start lbcwallet

### ISSUE THREAD

**Issue by moodyjon** [lbryio/lbry-sdk#3661]
https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true
I might have seen this in other tests in the past... Could it be infrastructure? No error message from `lbcwallet` regarding why it could not start.

```
test_reorg_change_claim_height (integration.takeovers.test_resolve_command.ResolveAfterReorg) ... 2022-09-10 03:09:46,481 - asyncio - WARNING - Executing <Task pending coro=<CommandTestCase.asyncSetUp() running at /home/runner/work/lbry-sdk/lbry-sdk/lbry/testcase.py:411> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/futures.py:351, <TaskWakeupMethWrapper object at 0x7f5bd1562d90>()] created at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:395> cb=[_run_until_complete_cb() at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:157] created at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:566> took 0.451 seconds
[630](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:631)
2022-09-10 03:09:47,517 - elasticsearch - WARNING - GET http://localhost:9200/_template/0f9a239dfd704949abdd6bd8f103658dclaims [status:404 request:0.004s]
[631](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:632)
2022-09-10 03:09:48,812 - asyncio - WARNING - Executing <Task pending coro=<CommandTestCase.asyncSetUp() running at /home/runner/work/lbry-sdk/lbry-sdk/lbry/testcase.py:411> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7f5bd144c8d0>()] created at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/tasks.py:642> cb=[_run_until_complete_cb() at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:157] created at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:566> took 0.299 seconds
[632](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:633)
2022-09-10 03:09:48,908 - lbry.wallet.network - WARNING - wait reconnect+keepalive
[633](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:634)
2022-09-10 03:09:54,657 - hub.scribe.daemon - ERROR - connection problem - is your daemon running?  Retrying occasionally...
[634](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:635)
2022-09-10 03:09:54,728 - hub.scribe.daemon - ERROR - connection problem - is your daemon running?  Retrying occasionally...
[635](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:636)
2022-09-10 03:09:55,978 - lbry.wallet.orchstr8.node - ERROR - failed to start lbcwallet
[636](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:637)
Traceback (most recent call last):
[637](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:638)
  File "/home/runner/work/lbry-sdk/lbry-sdk/lbry/wallet/orchstr8/node.py", line 570, in start
[638](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:639)
    assert not self.protocol.stopped.is_set()
[639](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:640)
AssertionError
[640](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:641)
ERROR
```

```
======================================================================
[821](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:822)
ERROR: test_reorg_change_claim_height (integration.takeovers.test_resolve_command.ResolveAfterReorg)
[822](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:823)
----------------------------------------------------------------------
[823](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:824)
Traceback (most recent call last):
[824](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:825)
  File "/home/runner/work/lbry-sdk/lbry-sdk/lbry/testcase.py", line 145, in run
[825](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:826)
    self.loop.run_until_complete(maybe_coroutine)
[826](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:827)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
[827](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:828)
    return future.result()
[828](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:829)
  File "/home/runner/work/lbry-sdk/lbry-sdk/tests/integration/takeovers/test_resolve_command.py", line 1683, in test_reorg_change_claim_height
[829](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:830)
    await asyncio.wait_for(self.on_header(209), 3.0)
[830](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:831)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
[831](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:832)
    raise futures.TimeoutError()
[832](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:833)
concurrent.futures._base.TimeoutError
[833](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:834)

[834](https://github.com/moodyjon/lbry-sdk/runs/8281334226?check_suite_focus=true#step:11:835)
----------------------------------------------------------------------
```

**Comment by moodyjon** [comment]
Another:
https://github.com/moodyjon/lbry-sdk/actions/runs/3062364236/jobs/4943257751

**Comment by moodyjon** [comment]
Another:
https://github.com/moodyjon/lbry-sdk/actions/runs/3082987938/jobs/4983363606
https://github.com/moodyjon/lbry-sdk/actions/runs/3082990425/jobs/4983369899

**Comment by moodyjon** [comment]
Another, but in test_reorg_drop_claim:
https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002310236

**Comment by moodyjon** [comment]
Another:
https://github.com/moodyjon/lbry-sdk/actions/runs/3102674973/jobs/5025214220
https://github.com/moodyjon/lbry-sdk/actions/runs/3102675530/jobs/5025215766
