### ISSUE TITLE
test_wallet_syncing_status: AssertionError: True is not false

### ISSUE THREAD

**Issue by moodyjon** [lbryio/lbry-sdk#3662]
This is happening right at the beginning of the test. Possible setup issue. Do we wait for an initial sync to finish?

```
    async def test_wallet_syncing_status(self):
        address = await self.daemon.jsonrpc_address_unused()
        self.assertFalse(self.daemon.jsonrpc_wallet_status()['is_syncing']).  <<<<<<<<<<<<< Failed
```

https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true

```
1944
test_wallet_syncing_status (integration.blockchain.test_wallet_commands.WalletCommands) ... 2022-09-10 14:44:55,125 - asyncio - WARNING - Executing <Task pending coro=<CommandTestCase.asyncSetUp() running at /home/runner/work/lbry-sdk/lbry-sdk/lbry/testcase.py:411> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/futures.py:351, <TaskWakeupMethWrapper object at 0x7ff51061e350>()] created at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:395> cb=[_run_until_complete_cb() at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:157] created at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:566> took 0.286 seconds
[1945](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1946)
2022-09-10 14:44:55,722 - elasticsearch - WARNING - GET http://localhost:9200/_template/6e733a1e9efd4842bce5cb3606e4403bclaims [status:404 request:0.003s]
[1946](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1947)
2022-09-10 14:44:56,460 - lbry.wallet.network - INFO - 1 possible spv servers to try (1 urls in config)
[1947](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1948)
2022-09-10 14:44:56,462 - lbry.wallet.network - INFO - localhost:50002 has latency of 0.84ms (available: True, height: 200)
[1948](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1949)
2022-09-10 14:44:56,470 - lbry.wallet.network - INFO - Connected to spv server localhost:50002
[1949](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1950)
2022-09-10 14:44:56,470 - lbry.wallet.network - DEBUG - send server.version('0.110.0', '0.110.0') to localhost:50002 (30 timeout)
[1950](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1951)
2022-09-10 14:44:56,471 - lbry.wallet.network - DEBUG - send version request to localhost:50002
[1951](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1952)
2022-09-10 14:44:56,473 - lbry.wallet.network - DEBUG - get spv server features localhost:50002
[1952](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1953)
2022-09-10 14:44:56,473 - lbry.wallet.network - DEBUG - send server.features() to localhost:50002 (30 timeout)
[1953](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1954)
2022-09-10 14:44:56,476 - lbry.wallet.network - DEBUG - response server.features() from localhost:50002 (30 timeout) -> {'hosts': {}, 'pruning': None, 'server_version': '0.107.0', 'protocol_min': '0.54.0', 'protocol_max': '0.199.0', 'genesis_hash': '6e3fcf1299d4ec5d79c3a4c91d624a4acf9e2e173d95a1a0504f677669687556', 'description': '', 'payment_address': '', 'donation_address': '', 'daily_fee': '0', 'hash_function': 'sha256', 'trending_algorithm': 'fast_ar'}
[1954](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1955)
2022-09-10 14:44:56,476 - lbry.wallet.network - DEBUG - discover other hubs localhost:50002
[1955](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1956)
2022-09-10 14:44:56,476 - lbry.wallet.network - DEBUG - send server.peers.subscribe() to localhost:50002 (30 timeout)
[1956](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1957)
2022-09-10 14:44:56,479 - lbry.wallet.network - DEBUG - response server.peers.subscribe() from localhost:50002 (30 timeout) -> []
[1957](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1958)
2022-09-10 14:44:56,479 - lbry.wallet.network - INFO - subscribe to headers localhost:50002
[1958](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1959)
2022-09-10 14:44:56,479 - lbry.wallet.network - DEBUG - send blockchain.headers.subscribe(True,) to localhost:50002 (30 timeout)
[1959](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1960)
2022-09-10 14:44:56,481 - lbry.wallet.network - DEBUG - response blockchain.headers.subscribe(True,) from localhost:50002 (30 timeout) -> {'hex': '0000003086a75128da6e0fc9486612c7f434c2e2ee0b9180c50c75c4b30e0e98c652d18d2c24ae0587caad70ca88f7e5b12b5ead8341de44f11dad19b60c05a83500d6e3010000000000000000000000000000000000000000000000000000000000000007a31c63ffff7f2002000000', 'height': 200}
[1960](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1961)
2022-09-10 14:44:56,482 - lbry.wallet.network - INFO - maintaining connection to spv server localhost:50002
[1961](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1962)
2022-09-10 14:44:56,482 - lbry.wallet.network - WARNING - wait reconnect+keepalive
[1962](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1963)
2022-09-10 14:44:56,483 - lbry.wallet.network - DEBUG - send blockchain.block.headers(0, 2001, 0, False) to localhost:50002 (30 timeout)
[... response elided ...]
[1964](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1965)
2022-09-10 14:44:56,491 - lbry.wallet.network - DEBUG - send blockchain.block.headers(201, 2001, 0, False) to localhost:50002 (30 timeout)
[1965](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1966)
2022-09-10 14:44:56,497 - lbry.wallet.network - DEBUG - response blockchain.block.headers(201, 2001, 0, False) from localhost:50002 (30 timeout) -> {'hex': '', 'count': 0, 'max': 40960}
[1966](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1967)
2022-09-10 14:44:56,518 - lbry.wallet.network - DEBUG - send blockchain.address.subscribe('mp5mc6SiaKe7zT4LhFxTRPw5RgF8hjPJLG', 'mtxbATCtbPVEP8xAEYuZ6drFsHrmZeAZQv', 'mn4sQvaNwPhMJisbeKQGzmgAckUAUDCZEm', 'mp2ZT7i9YeSZujdMwdCSR4S8Tj2toEm6ph', 'mqtfw4L1mJFEkafw37pwQ1dB5FhHiScfiC', 'mk9hcxxnXJuhV7e21cWVAyuoeztRUuwu38', 'mwRnCWzbcsh5SybcsppigtxDrNZPs9kgek', 'n47y44ENP5cxuvKZfS2up2HLzXmBKBQy34', 'mqeRHW9wCCYDJbdtWSfHcjTbRXUPdKz6au', 'mfvUw54W57CqFXsHyqXe3nsyu94XtXLqZe', 'mvt6TVvsjq5ghGvok9S7dtbBNFD4niNNsS', 'mw8tF6NB4PYfcvbPcoR8c8hWxkacELoeAu', 'mjRLUE9wqcky4acvDvH5bi6FaH4J5WSHyZ', 'n3hRPy5gEq2BrXduLsDUD5Q4VJcRUL3jsA', 'n3U1ND41AHb1jfW7jamF78Pbxa364tH64t', 'mwgXLuTGG6ax1JDfmyaCpY34QeB7nE7Fqz', 'moBmnnD6vjJUGE6tsk6ZwP3ZCLxMHTku9s', 'mt3m8R1Cqm1UtvQqexgMABUdq9CTJDU3fv', 'mj8gXY5A4AedwukNQ83XpJBeKLmypMn4iY', 'mjF2YW7AfsyexC5kmcT7yxWMFoBJCFvR1T') to localhost:50002 (30 timeout)
[1967](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1968)
2022-09-10 14:44:56,598 - lbry.wallet.network - DEBUG - response blockchain.address.subscribe('mp5mc6SiaKe7zT4LhFxTRPw5RgF8hjPJLG', 'mtxbATCtbPVEP8xAEYuZ6drFsHrmZeAZQv', 'mn4sQvaNwPhMJisbeKQGzmgAckUAUDCZEm', 'mp2ZT7i9YeSZujdMwdCSR4S8Tj2toEm6ph', 'mqtfw4L1mJFEkafw37pwQ1dB5FhHiScfiC', 'mk9hcxxnXJuhV7e21cWVAyuoeztRUuwu38', 'mwRnCWzbcsh5SybcsppigtxDrNZPs9kgek', 'n47y44ENP5cxuvKZfS2up2HLzXmBKBQy34', 'mqeRHW9wCCYDJbdtWSfHcjTbRXUPdKz6au', 'mfvUw54W57CqFXsHyqXe3nsyu94XtXLqZe', 'mvt6TVvsjq5ghGvok9S7dtbBNFD4niNNsS', 'mw8tF6NB4PYfcvbPcoR8c8hWxkacELoeAu', 'mjRLUE9wqcky4acvDvH5bi6FaH4J5WSHyZ', 'n3hRPy5gEq2BrXduLsDUD5Q4VJcRUL3jsA', 'n3U1ND41AHb1jfW7jamF78Pbxa364tH64t', 'mwgXLuTGG6ax1JDfmyaCpY34QeB7nE7Fqz', 'moBmnnD6vjJUGE6tsk6ZwP3ZCLxMHTku9s', 'mt3m8R1Cqm1UtvQqexgMABUdq9CTJDU3fv', 'mj8gXY5A4AedwukNQ83XpJBeKLmypMn4iY', 'mjF2YW7AfsyexC5kmcT7yxWMFoBJCFvR1T') from localhost:50002 (30 timeout) -> [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[1968](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1969)
2022-09-10 14:44:56,633 - lbry.wallet.network - DEBUG - send blockchain.address.subscribe('n3XwJZJQA1KbR8yaMg8TgwqM2KJHFf4BwM', 'mi9F7BCcoVbyQ6fNn2Ea8YAQhDStqZSY54', 'mkixDCzaZYL2ZFwGhBVguK4JPBGmcMFFD7', 'n3gexKAXgppAJGkD5cU8rH7CYvRgidjGxG', 'mhunvYN1Cj4MAhh2XTNABHGYfMzvewWjKG', 'mwP9viTZRwinKhrota69RUfHJ8njHuzj3s') to localhost:50002 (30 timeout)
[1969](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1970)
2022-09-10 14:44:56,645 - lbry.wallet.network - DEBUG - response blockchain.address.subscribe('n3XwJZJQA1KbR8yaMg8TgwqM2KJHFf4BwM', 'mi9F7BCcoVbyQ6fNn2Ea8YAQhDStqZSY54', 'mkixDCzaZYL2ZFwGhBVguK4JPBGmcMFFD7', 'n3gexKAXgppAJGkD5cU8rH7CYvRgidjGxG', 'mhunvYN1Cj4MAhh2XTNABHGYfMzvewWjKG', 'mwP9viTZRwinKhrota69RUfHJ8njHuzj3s') from localhost:50002 (30 timeout) -> [None, None, None, None, None, None]
[1970](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1971)
2022-09-10 14:44:57,068 - lbry.wallet.network - DEBUG - send blockchain.address.get_history('mp5mc6SiaKe7zT4LhFxTRPw5RgF8hjPJLG',) to localhost:50002 (30 timeout)
[1971](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1972)
2022-09-10 14:44:57,072 - lbry.wallet.network - DEBUG - response blockchain.address.get_history('mp5mc6SiaKe7zT4LhFxTRPw5RgF8hjPJLG',) from localhost:50002 (30 timeout) -> [{'tx_hash': '5954d9cd87c327eafd41213e937102b538e74b814baa441b986ed6aefb311220', 'height': 0, 'fee': 1717}]
[1972](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1973)
2022-09-10 14:44:57,072 - lbry.wallet.network - DEBUG - send blockchain.transaction.get_batch('5954d9cd87c327eafd41213e937102b538e74b814baa441b986ed6aefb311220',) to localhost:50002 (30 timeout)
[1973](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1974)
2022-09-10 14:44:57,076 - lbry.wallet.network - DEBUG - response blockchain.transaction.get_batch('5954d9cd87c327eafd41213e937102b538e74b814baa441b986ed6aefb311220',) from localhost:50002 (30 timeout) -> {'5954d9cd87c327eafd41213e937102b538e74b814baa441b986ed6aefb311220': ['010000000b005cf1e21025f99e5790359e17a8d8b86ad56bbbccc8d1ff9b9da5867df0abb1000000006b483045022100f3574e42e7670b929ffb47a316f05092ff57811daeda577f992eccc5b856aaed02200229c6b7c455efb1bbcbdb19500de84364901c9b99e20b233f7a448851b8463b012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff017614e8c98e0947e98e75c96b2e72038a437b0f35d3222f6dfd2f90ef3977d7000000006a47304402200a1d9cbf425673f2436547c52f39993e330fe2b831eecb399cd78538d8b919d5022029bf9bb848e9064cba03f6c6644bbdb61be018760a3b470219f6f3908e84b4a0012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff01a1bc399a379a101c9540d2aa162d6afe0bb95cd875396a00381f5dfe35a9c7000000006b483045022100eec3297513d339c2184f0a2501783970e776e784356f470c63de1ecc4261859102203c33b4e5b1f9df354a607c658e6b698ac464d6a5a7b71b3e30bd78d1dad2518e012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff024ca8e49b3c65179775fefff129499c4d82d3ff13b1450f6096cbfa9c9c8372000000006b483045022100b0a43f7f1c56f9f341f98589a767f747e2692a3a3e871d759d442fe9f4e704550220640731137ae50f7df92092bb4f6e3f9e39865ba509efd5163616c70bb68172c5012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff04c2149ebacb0493d35d52ffb040eabbc0627079e1dc76f20d8d5056a8b12293000000006a47304402205c59437eb4fff31f464664f5bdeeda22ea3f26195aadc7e4c19cf6020042797b0220715e44c9b4e7cc23f5488e2a91b5ca070a64f07e446b5a390402f7caadc61789012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff081ec71684c2f0fb653f97d414ca5e7117b41cc5c0223e9cee77ba5d807fd60f000000006a47304402201c2d81564ccf3356b967af395e2953d519335d347c0091b284de493a87dd4f5d02206089ca8b24ab3906ab90644cb6856da9c311a7dfa435a54432baabf2474d1b8a012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff0c4d86544509e661385ea0b4c3bb35d70e521b6df6f6b0fb7d868eeed5758e0b000000006b4830450221008db6bec6a55438e9a5c263d84447c4aa3c020af5a80155670f80ffe599420c0e022058fc96ad9a2ff0a495a55baab01c0bb5ba6e342ed8185f5a2cefb4f06c81a3df012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff0e93fac9bfc8f8f9f926f283661a0bd3ffbfa35466bc8b62f38b9f881f87b2ce000000006b483045022100b1e3ee8eac5550d654e88576d49f525fe1cf5aea73d219ea15549ac2619faf9b02203af044cc6426b45d947503706163622bb870c137aeb3fefa7d1bde28558a2846012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff1277523d705b51a9045d234a97b96bc49bda22c4565f71dd1167e1706205445a000000006b4830450221008edc62986095eda52cfdebf6e556a1b5906957c34eb24b93095a10dc39b8629b022062f0e3115db655ee1d15a7bdfc71efda36844cec148b309263a53cf009cfeb72012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff1379ab36671818e168a6185f5a1289b46463ec7ec7b90724ea112b818b5a0d0b000000006b483045022100985b04dd277ec7ba2d03e7003d2c2859479bbf1e275a9fe0caeecd9efa80f89a02205682c7e43304332915d422ac9d87599e8b851da3f8c31709812e7b1e02b46215012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff13e5cb2529cabcb87bdcdac5cbc77eed8dfb2f185cfe87a1ce03d9ba358a54ff000000006a4730440220381e318d11e8c868dd2d7a60c3942bcc65170c26410917296646e50dbef4490502201df46b308d8a06abdb26d96963a351c7bd93b0ff86c7b701abd47fe427585e82012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff0200ca9a3b000000001976a9145df5cf71197ca3a890b7c60d09227cfe90cba1bc88ac4bdaf505000000001976a9140a297f206cb51a6fa45238a1178b3b79141b4e7688ac00000000', {'block_height': -1}]}
[1974](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1975)
2022-09-10 14:44:57,104 - lbry.wallet.network - DEBUG - send blockchain.address.subscribe('n2ZCeq1LBNxPxPcJ57jRnqhvkh2sU9pUCe',) to localhost:50002 (30 timeout)
[1975](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1976)
2022-09-10 14:44:57,108 - lbry.wallet.network - DEBUG - response blockchain.address.subscribe('n2ZCeq1LBNxPxPcJ57jRnqhvkh2sU9pUCe',) from localhost:50002 (30 timeout) -> [None]
[1976](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1977)
2022-09-10 14:44:57,357 - lbry.wallet.network - DEBUG - send blockchain.address.get_history('mp5mc6SiaKe7zT4LhFxTRPw5RgF8hjPJLG',) to localhost:50002 (30 timeout)
[1977](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1978)
2022-09-10 14:44:57,369 - lbry.wallet.network - DEBUG - response blockchain.address.get_history('mp5mc6SiaKe7zT4LhFxTRPw5RgF8hjPJLG',) from localhost:50002 (30 timeout) -> [{'tx_hash': '5954d9cd87c327eafd41213e937102b538e74b814baa441b986ed6aefb311220', 'height': 201}]
[1978](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1979)
2022-09-10 14:44:57,370 - lbry.wallet.network - DEBUG - send blockchain.transaction.get_batch('5954d9cd87c327eafd41213e937102b538e74b814baa441b986ed6aefb311220',) to localhost:50002 (30 timeout)
[1979](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1980)
2022-09-10 14:44:57,379 - lbry.wallet.network - DEBUG - response blockchain.transaction.get_batch('5954d9cd87c327eafd41213e937102b538e74b814baa441b986ed6aefb311220',) from localhost:50002 (30 timeout) -> {'5954d9cd87c327eafd41213e937102b538e74b814baa441b986ed6aefb311220': ['010000000b005cf1e21025f99e5790359e17a8d8b86ad56bbbccc8d1ff9b9da5867df0abb1000000006b483045022100f3574e42e7670b929ffb47a316f05092ff57811daeda577f992eccc5b856aaed02200229c6b7c455efb1bbcbdb19500de84364901c9b99e20b233f7a448851b8463b012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff017614e8c98e0947e98e75c96b2e72038a437b0f35d3222f6dfd2f90ef3977d7000000006a47304402200a1d9cbf425673f2436547c52f39993e330fe2b831eecb399cd78538d8b919d5022029bf9bb848e9064cba03f6c6644bbdb61be018760a3b470219f6f3908e84b4a0012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff01a1bc399a379a101c9540d2aa162d6afe0bb95cd875396a00381f5dfe35a9c7000000006b483045022100eec3297513d339c2184f0a2501783970e776e784356f470c63de1ecc4261859102203c33b4e5b1f9df354a607c658e6b698ac464d6a5a7b71b3e30bd78d1dad2518e012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff024ca8e49b3c65179775fefff129499c4d82d3ff13b1450f6096cbfa9c9c8372000000006b483045022100b0a43f7f1c56f9f341f98589a767f747e2692a3a3e871d759d442fe9f4e704550220640731137ae50f7df92092bb4f6e3f9e39865ba509efd5163616c70bb68172c5012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff04c2149ebacb0493d35d52ffb040eabbc0627079e1dc76f20d8d5056a8b12293000000006a47304402205c59437eb4fff31f464664f5bdeeda22ea3f26195aadc7e4c19cf6020042797b0220715e44c9b4e7cc23f5488e2a91b5ca070a64f07e446b5a390402f7caadc61789012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff081ec71684c2f0fb653f97d414ca5e7117b41cc5c0223e9cee77ba5d807fd60f000000006a47304402201c2d81564ccf3356b967af395e2953d519335d347c0091b284de493a87dd4f5d02206089ca8b24ab3906ab90644cb6856da9c311a7dfa435a54432baabf2474d1b8a012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff0c4d86544509e661385ea0b4c3bb35d70e521b6df6f6b0fb7d868eeed5758e0b000000006b4830450221008db6bec6a55438e9a5c263d84447c4aa3c020af5a80155670f80ffe599420c0e022058fc96ad9a2ff0a495a55baab01c0bb5ba6e342ed8185f5a2cefb4f06c81a3df012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff0e93fac9bfc8f8f9f926f283661a0bd3ffbfa35466bc8b62f38b9f881f87b2ce000000006b483045022100b1e3ee8eac5550d654e88576d49f525fe1cf5aea73d219ea15549ac2619faf9b02203af044cc6426b45d947503706163622bb870c137aeb3fefa7d1bde28558a2846012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff1277523d705b51a9045d234a97b96bc49bda22c4565f71dd1167e1706205445a000000006b4830450221008edc62986095eda52cfdebf6e556a1b5906957c34eb24b93095a10dc39b8629b022062f0e3115db655ee1d15a7bdfc71efda36844cec148b309263a53cf009cfeb72012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff1379ab36671818e168a6185f5a1289b46463ec7ec7b90724ea112b818b5a0d0b000000006b483045022100985b04dd277ec7ba2d03e7003d2c2859479bbf1e275a9fe0caeecd9efa80f89a02205682c7e43304332915d422ac9d87599e8b851da3f8c31709812e7b1e02b46215012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff13e5cb2529cabcb87bdcdac5cbc77eed8dfb2f185cfe87a1ce03d9ba358a54ff000000006a4730440220381e318d11e8c868dd2d7a60c3942bcc65170c26410917296646e50dbef4490502201df46b308d8a06abdb26d96963a351c7bd93b0ff86c7b701abd47fe427585e82012103e3dc9a1d0ef91d99d7d1b6d477b3b00fb09c3ae58d9332bfd71ecdf4e0f379fcffffffff0200ca9a3b000000001976a9145df5cf71197ca3a890b7c60d09227cfe90cba1bc88ac4bdaf505000000001976a9140a297f206cb51a6fa45238a1178b3b79141b4e7688ac00000000', {'block_height': 201, 'merkle': ['2eea5af17bdc39d5629a2d3f70b667454a99009f191b8e6f4d6dfddf63a898ce'], 'pos': 1}]}
[1980](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1981)
2022-09-10 14:44:57,405 - lbry.wallet.network - INFO - closing connection to localhost:50002
[1981](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1982)
2022-09-10 14:44:57,405 - lbry.wallet.network - INFO - connection lost to localhost:50002
[1982](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1983)
2022-09-10 14:44:57,405 - lbry.wallet.network - INFO - network loop finished
[1983](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1984)
2022-09-10 14:44:57,406 - lbry.wallet.network - DEBUG - Connection lost: localhost:50002
[1984](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:1985)
FAIL
```

```
======================================================================
[3664](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3665)
FAIL: test_wallet_syncing_status (integration.blockchain.test_wallet_commands.WalletCommands)
[3665](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3666)
----------------------------------------------------------------------
[3666](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3667)
Traceback (most recent call last):
[3667](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3668)
  File "/home/runner/work/lbry-sdk/lbry-sdk/lbry/testcase.py", line 145, in run
[3668](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3669)
    self.loop.run_until_complete(maybe_coroutine)
[3669](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3670)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
[3670](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3671)
    return future.result()
[3671](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3672)
  File "/home/runner/work/lbry-sdk/lbry-sdk/tests/integration/blockchain/test_wallet_commands.py", line 25, in test_wallet_syncing_status
[3672](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3673)
    self.assertFalse(self.daemon.jsonrpc_wallet_status()['is_syncing'])
[3673](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3674)
AssertionError: True is not false
[3674](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3675)

[3675](https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true#step:11:3676)
----------------------------------------------------------------------
```

**Comment by moodyjon** [comment]
Another one: https://github.com/moodyjon/lbry-sdk/runs/8285365273?check_suite_focus=true
