### ISSUE TITLE
test_unhandled_sqlite_misuse: AssertionError: False is not true : this test failing means either the sqlite race conditions have been fixed in cpython or the test max_attempts needs to be increased

### ISSUE THREAD

**Issue by moodyjon** [lbryio/lbry-sdk#3671]
https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726

```
sqlite3 2.6.0/python 3.7.13 (default, May  4 2022, 08:45:32) did not raise SQLITE_MISUSE within 80000 attempts of the race condition
```

```
478
======================================================================
[479](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:480)
FAIL: test_unhandled_sqlite_misuse (tests.unit.wallet.test_database.TestSQLiteRace)
[480](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:481)
----------------------------------------------------------------------
[481](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:482)
Traceback (most recent call last):
[482](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:483)
  File "/home/runner/work/lbry-sdk/lbry-sdk/lbry/testcase.py", line 145, in run
[483](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:484)
    self.loop.run_until_complete(maybe_coroutine)
[484](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:485)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
[485](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:486)
    return future.result()
[486](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:487)
  File "/home/runner/work/lbry-sdk/lbry-sdk/tests/unit/wallet/test_database.py", line 535, in test_unhandled_sqlite_misuse
[487](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:488)
    self.assertTrue(False, 'this test failing means either the sqlite race conditions '
[488](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:489)
AssertionError: False is not true : this test failing means either the sqlite race conditions have been fixed in cpython or the test max_attempts needs to be increased
[489](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:490)

[490](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:491)
----------------------------------------------------------------------
[491](https://github.com/moodyjon/lbry-sdk/actions/runs/3091793824/jobs/5002309726#step:9:492)
Ran 348 tests in 214.348s
```

**Comment by moodyjon** [comment]
Another:
https://github.com/moodyjon/lbry-sdk/actions/runs/3091644759/jobs/5001968859
