### ISSUE TITLE
various tests: hub.herald.session - ERROR - TCP server failed to listen on 127.0.0.1:50002 :OSError(98, "error while attempting to bind on address ('127.0.0.1', 50002): address already in use")

### ISSUE THREAD

**Issue by moodyjon** [lbryio/lbry-sdk#3673]
```
4439 test_source_filter (integration.claims.test_claim_commands.ClaimSearchCommand) ... 2022-09-21 00:47:00,475 - asyncio - WARNING - Executing <Task pending coro=<CommandTestCase.asyncSetUp() running at /home/runner/work/lbry-sdk/lbry-sdk/lbry/testcase.py:415> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/futures.py:351, <TaskWakeupMethWrapper object at 0x7f5af08fd450>()] created at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:395> cb=[_run_until_complete_cb() at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:157] created at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:566> took 0.504 seconds
[4440](https://github.com/moodyjon/lbry-sdk/actions/runs/3094377560/jobs/5007689165#step:11:4441)
2022-09-21 00:47:01,495 - elasticsearch - WARNING - GET http://localhost:9200/_template/783bfa0b44764850859fa3e1d4f4daf4claims [status:404 request:0.003s]
[4441](https://github.com/moodyjon/lbry-sdk/actions/runs/3094377560/jobs/5007689165#step:11:4442)
2022-09-21 00:47:02,147 - asyncio - WARNING - Executing <Task pending coro=<CommandTestCase.asyncSetUp() running at /home/runner/work/lbry-sdk/lbry-sdk/lbry/testcase.py:415> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/futures.py:351, <TaskWakeupMethWrapper object at 0x7f5af05b3850>()] created at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:395> cb=[_run_until_complete_cb() at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:157] created at /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py:566> took 0.210 seconds
[4442](https://github.com/moodyjon/lbry-sdk/actions/runs/3094377560/jobs/5007689165#step:11:4443)
2022-09-21 00:47:02,659 - hub.herald.session - ERROR - TCP server failed to listen on 127.0.0.1:50002 :OSError(98, "error while attempting to bind on address ('127.0.0.1', 50002): address already in use")
[4443](https://github.com/moodyjon/lbry-sdk/actions/runs/3094377560/jobs/5007689165#step:11:4444)
2022-09-21 00:47:02,787 - lbry.wallet.network - WARNING - Connecting to localhost:50002 failed
[4444](https://github.com/moodyjon/lbry-sdk/actions/runs/3094377560/jobs/5007689165#step:11:4445)
2022-09-21 00:47:02,787 - lbry.wallet.network - WARNING - failed to connect to any spv servers, retrying later
[4445](https://github.com/moodyjon/lbry-sdk/actions/runs/3094377560/jobs/5007689165#step:11:4446)
2022-09-21 00:47:32,802 - lbry.wallet.network - WARNING - Connecting to localhost:50002 failed
[4446](https://github.com/moodyjon/lbry-sdk/actions/runs/3094377560/jobs/5007689165#step:11:4447)
2022-09-21 00:47:32,802 - lbry.wallet.network - WARNING - failed to connect to any spv servers, retrying later
[4447](https://github.com/moodyjon/lbry-sdk/actions/runs/3094377560/jobs/5007689165#step:11:4448)
2022-09-21 00:48:02,814 - lbry.wallet.network - WARNING - Connecting to localhost:50002 failed
[4448](https://github.com/moodyjon/lbry-sdk/actions/runs/3094377560/jobs/5007689165#step:11:4449)
2022-09-21 00:48:02,814 - lbry.wallet.network - WARNING - failed to connect to any spv servers, retrying later
[4449](https://github.com/moodyjon/lbry-sdk/actions/runs/3094377560/jobs/5007689165#step:11:4450)
2022-09-21 00:48:32,827 - lbry.wallet.network - WARNING - Connecting to localhost:50002 failed
[4450](https://github.com/moodyjon/lbry-sdk/actions/runs/3094377560/jobs/5007689165#step:11:4451)
2022-09-21 00:48:32,827 - lbry.wallet.network - WARNING - failed to connect to any spv servers, retrying later
```

**Comment by moodyjon** [comment]
One in a unit test:
https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192

```
478
======================================================================
[479](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:480)
ERROR: test_multiple_servers (tests.unit.torrent.test_tracker.UDPTrackerClientTestCase)
[480](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:481)
----------------------------------------------------------------------
[481](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:482)
Traceback (most recent call last):
[482](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:483)
  File "/home/runner/work/lbry-sdk/lbry-sdk/lbry/testcase.py", line 138, in run
[483](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:484)
    self.loop.run_until_complete(self.asyncSetUp())
[484](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:485)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
[485](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:486)
    return future.result()
[486](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:487)
  File "/home/runner/work/lbry-sdk/lbry-sdk/tests/unit/torrent/test_tracker.py", line 16, in asyncSetUp
[487](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:488)
    await self.add_server()
[488](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:489)
  File "/home/runner/work/lbry-sdk/lbry-sdk/tests/unit/torrent/test_tracker.py", line 23, in add_server
[489](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:490)
    transport, _ = await self.loop.create_datagram_endpoint(lambda: server, local_addr=("127.0.0.1", port))
[490](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:491)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py", line 1256, in create_datagram_endpoint
[491](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:492)
    raise exceptions[0]
[492](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:493)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py", line 1240, in create_datagram_endpoint
[493](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:494)
    sock.bind(local_address)
[494](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:495)
OSError: [Errno 98] Address already in use
[495](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:496)

[496](https://github.com/moodyjon/lbry-sdk/actions/runs/3094272495/jobs/5007471192#step:9:497)
----------------------------------------------------------------------
```
