### ISSUE TITLE
client stops retrying hub connections

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#3699]
```2022-10-30 02:37:44,292 INFO     lbry.wallet.network:269: b-hub1.odysee.com:50001 has latency of 29.81ms (available: True, height: 1250272)
2022-10-30 02:37:44,293 INFO     lbry.wallet.network:269: s-hub1.odysee.com:50001 has latency of 31.72ms (available: True, height: 1250272)
2022-10-30 02:37:44,294 INFO     lbry.wallet.network:269: a-hub1.odysee.com:50001 has latency of 31.77ms (available: True, height: 1250272)
2022-10-30 02:37:44,294 INFO     lbry.wallet.network:269: c-hub1.odysee.com:50001 has latency of 32.09ms (available: True, height: 1250272)
2022-10-30 02:37:44,295 INFO     lbry.wallet.udp:232: closed udp spv server selection client
2022-10-30 02:37:50,295 WARNING  lbry.wallet.network:307: Connecting to b-hub1.odysee.com:50001 failed
2022-10-30 02:37:51,401 INFO     lbry.wallet.network:303: Connected to spv server s-hub1.odysee.com:50001
2022-10-30 02:37:59,689 INFO     lbry.dht.protocol.routing_table:312: join buckets 5
2022-10-30 02:37:59,690 INFO     lbry.dht.protocol.routing_table:312: join buckets 4
2022-10-30 02:37:59,690 INFO     lbry.dht.protocol.routing_table:312: join buckets 3
2022-10-30 02:37:59,690 INFO     lbry.dht.protocol.routing_table:312: join buckets 2
2022-10-30 02:37:59,690 INFO     lbry.dht.protocol.routing_table:312: join buckets 1
2022-10-30 02:38:05,867 INFO     lbry.dht.node:177: joined dht, 15 peers known in 4 buckets
2022-10-30 02:38:23,386 WARNING  lbry.wallet.network:75: timeout sending server.peers.subscribe to s-hub1.odysee.com:50001
2022-10-30 02:38:23,386 ERROR    lbry.wallet.network:219: wallet server connection loop crashed
Traceback (most recent call last):
  File "lbry/wallet/network.py", line 216, in loop_task_done_callback
  File "lbry/wallet/network.py", line 331, in network_loop
  File "lbry/wallet/network.py", line 76, in send_request```

**Comment by tzarebczan** [comment]
all Odysee youtube sync servers got stuck here for hours.
