### ISSUE TITLE
bittrex timeout prevents startup?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#3723]
```2022-12-14 07:08:13,217 WARNING  lbry.extras.daemon.exchange_rate_manager:94: Error trying to connect to exchange rate Bittrex: Cannot connect to host api.bittrex.com:443 ssl:default [Temporary failure in name resolution]
2022-12-14 07:10:14,467 WARNING  lbry.extras.daemon.exchange_rate_manager:86: Timed out fetching exchange rate from Bittrex.
2022-12-14 07:20:20,468 WARNING  lbry.extras.daemon.exchange_rate_manager:86: Timed out fetching exchange rate from CoinEx.
2022-12-14 07:20:20,469 WARNING  lbry.extras.daemon.exchange_rate_manager:86: Timed out fetching exchange rate from CoinEx.
2022-12-14 07:24:23,467 WARNING  lbry.extras.daemon.exchange_rate_manager:86: Timed out fetching exchange rate from Bittrex.
2022-12-14 07:26:24,467 WARNING  lbry.extras.daemon.exchange_rate_manager:86: Timed out fetching exchange rate from Bittrex.
2022-12-14 07:30:49,131 WARNING  lbry.extras.daemon.exchange_rate_manager:94: Error trying to connect to exchange rate CoinEx: Cannot connect to host api.coinex.com:443 ssl:default [Temporary failure in name resolution]
2022-12-14 07:30:49,147 WARNING  lbry.extras.daemon.exchange_rate_manager:94: Error trying to connect to exchange rate CoinEx: Cannot connect to host api.coinex.com:443 ssl:default [Temporary failure in name resolution]
2022-12-14 07:34:51,872 WARNING  lbry.extras.daemon.exchange_rate_manager:94: Error trying to connect to exchange rate Bittrex: Cannot connect to host api.bittrex.com:443 ssl:default [Temporary failure in name resolution]
2022-12-14 07:43:00,467 WARNING  lbry.extras.daemon.exchange_rate_manager:86: Timed out fetching exchange rate from Bittrex.
2022-12-14 07:46:53,468 WARNING  lbry.extras.daemon.exchange_rate_manager:86: Timed out fetching exchange rate from CoinEx.
2022-12-14 07:46:53,468 WARNING  lbry.extras.daemon.exchange_rate_manager:86: Timed out fetching exchange rate from CoinEx.
2022-12-14 07:48:51,468 WARNING  lbry.extras.daemon.exchange_rate_manager:86: Timed out fetching exchange rate from Bittrex.
2022-12-14 21:30:45,749 ERROR    lbry.extras.daemon.exchange_rate_manager:96: Exchange rate error (USDLBC from Bittrex):
Traceback (most recent call last):
  File "lbry/extras/daemon/exchange_rate_manager.py", line 77, in get_rate
  File "lbry/extras/daemon/exchange_rate_manager.py", line 125, in get_rate_from_response
ZeroDivisionError: float division by zero```

**Comment by Xyncgas** [comment]
bittrex has filed for bankruptcy
